### ISSUE TITLE
Import or Use pype outside of pype executable

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1034]
## Description
It would be great to be able use build pype as python modul which can be imported. That is not possible right now as many of initialization parts of pype are based on current environments and executable which started the initialization.

- To be able do that we have to change definition how to know that imported pype is from code or build.
- We also have to dicard use of pype settings before pype version usage is defined.
- Pype initialization also import pype inside before knowing which pype version is used (maybe won't when settings won't be loaded) which means that it is required to remove pype from `sys.modules` afterwards, but it is possible that meanwhile other part of code already imported and cached bad pype module.

[cuID:PYPE-1355]

**Comment by mkolar** [comment]
we decided that at the moment this doesn't have enough use for it to be justifiable
