### ISSUE TITLE
pillow 7.x does not support python 3.9

### ISSUE THREAD

**Issue by rjmoggach** [pypeclub/OpenPype#1043]
Automated install fails because it can't build Pillow 7.x with Python 3.9.

Workaround is possibly to install Pillow 8 which does support 3.9.

[cuID:PYPE-1184]

**Comment by robmoggach** [comment]
and I just saw there's a poetry.lock file so should I install the packages with that instead?

**Comment by antirotor** [comment]
Poetry is used for pype 3 and that is no ready for release yet. Please use release tags or checkout `2.0/main` branch. But ofc we are glad for testing 3.0 :)

About Python version - we are discussing it right now. But we are still trying to adhere to [vfx platform](https://vfxplatform.com/) so we are now supporting Python 3.7

**Comment by robmoggach** [comment]
My bad - I can't remember why I went with 3.9 - I'm going to stick with 2.0 for now. I'll make the shift a bit later and maybe contract it if I'm too busy.

**Comment by mkolar** [comment]
It's actually quite large discussion right now about the python version. We are for instance trying to make a consistent build on Mac OS, but with 3.7 it really is a challenge. While upgrading to 3.9 fully, has a potential to break a number of things, especially in the hosts that are a bit...ehm..behind. (Looking at you Maya and Nuke)

**Comment by robmoggach** [comment]
OT thankfully homebrew finally supports M1 and pyenv is building 2.7 and
3.7 on my macbook air - but it was frustrating in december to not have it

**Comment by antirotor** [comment]
related to #2523. Plan is to upgrade.
