### ISSUE TITLE
Maya: Look publishing - add extra attributes

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#107]
**Feature**

When publishing looks from Maya, it would be nice to have ability to add extra attributes to published look, like Arnolds *aiOpacity*, etc.

Maybe define in preset what attributes to include?

[cuID:PYPE-1375]

**Comment by BigRoy** [comment]
_Just adding some more details.._

Note that the current look publishing is already [able to identify "look attributes"](https://github.com/pypeclub/pype/blob/8f2b2b631cc5d3ad93eeb5ad3bc6110d32466ed3/pype/plugins/maya/publish/collect_look.py#L9-L53) however not renderer specific attributes like those for Arnold (prefixed with `ai` or vray usually prefixed with `vray` but just default Shape specific settings..

Be aware that some attributes can be tricky to collect as they might require "inputs" as opposed to just straight values. For example, some V-Ray Attributes allow you to connect textures to them, or even fully procedural shader networks (or even technically other dag nodes). This would all mean that these would need to be somehow included with the publish and potentially like shader textures included as remappable resources. (This is something to potentially take into account.)

**Comment by mkolar** [comment]
The description is a bit misleading. The reported problem is about render attributes on Yeti nodes. publishing and loading of this data is working well on standard shape nodes as @BigRoy mentioned. aiOpaque, subdivision and similar are being passed through correctly with the look if it doesn't have yeti in the assigned shapes.

**Comment by mkolar** [comment]
Thinking about this a bit more. The reason it doesn't work right now is because we''re counting on any geometry being references and then collect ref edits on any attributes assuming those are important for look development. However this cannot work on yeti nodes, because they are created with the groom directly in the lookdev workfile, hence no ref edits on them and we don't collect these as a result.

The preset that would drive this should be general enough to be able to include arbitrary node types as well.

**Comment by mkolar** [comment]
This should be split to separate tickets for yeti, vray, redshift and Arnold.

**Comment by antirotor** [comment]
> This should be split to separate tickets for yeti, vray, redshift and Arnold.

True but we need to change basic look collection and handling different Maya plugin in more universal abstract way.  I am processing Redshift now and Redshift is storing its attributes it its own unique typed set that needs to be detected.

**Comment by antirotor** [comment]
This is somewhat covered. I am closing it now. Feel free to re-open if something is missing.
