### ISSUE TITLE
Launch arguments of applications

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1094]
## Description
Now we store launch arguments of each application as list `[<executable path>, <launch arguments>]` which means that for each executable arguments must be filled and user would have to fill them too in local settings. Also want to mention that multiple arguments are stored as one string which may cause issues with bad parsing during launch. Result of current settings is dictionary of list of lists.
```json
{
    "windows": [
        ["my/executable_1.exe", "--quite"],
        ["my/executabke_2.exe", "--quite"]
    ],
    "linux": [],
    "darwin": []
}
```

## Suggested solution
We should store executables and launch arguments separatelly and launch arguments would be same for all executables (per platform). Change structure to:
```json
{
    "windows": {
        "executables": ["my/executable_1.exe", "my/executabke_2.exe"],
        "args": ["--quite"]
    }
}
```

## GUI look
Not sure how to visualize these settings as it may be confusing to set it.

### Current look
![image](https://user-images.githubusercontent.com/43494761/110108311-4f1bc900-7dac-11eb-864e-b1798091c47c.png)

### Suggested look
(please ignore only `+` buttons)
![image](https://user-images.githubusercontent.com/43494761/110113057-d66c3b00-7db2-11eb-83a5-1fca566c9f57.png)

### Suggested look 2
![image](https://user-images.githubusercontent.com/43494761/110113640-af623900-7db3-11eb-9ab7-572470c7845d.png)

**Comment by mkolar** [comment]
this has been solved in 3.0
