### ISSUE TITLE
Launcher: started action indicator

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#1102]
## Feature

It would be nice to have some visual response when running action from launcher. For example on my setup it takes almost 10 sec between clicking on Maya icon to launch it and Maya splash screen to pop up and until then I have no clue what is happening (if anything). Solution would be some visual indication that action has started, like icon fading in/out or some message in status bar with timeout on disappearing.

**Comment by mkolar** [comment]
this was already solved. https://github.com/pypeclub/OpenPype/pull/1143
