### ISSUE TITLE
Library loader does not show same families as Loader

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1103]
## Description
- library loader still shows bad families from version document where are not in correct order which is already fixed in loader tool

![image](https://user-images.githubusercontent.com/43494761/110511057-207f5480-8104-11eb-87da-147cf31411e4.png)

[cuID:PYPE-1149]

**Comment by mkolar** [comment]
@iLLiCiTiT could you please check if this is still happening?

**Comment by iLLiCiTiT** [comment]
Checked, it's showing right in both now.
