### ISSUE TITLE
edit - convert old presets to settings

### ISSUE THREAD

**Issue by mkolar** [pypeclub/OpenPype#1120]
As we migrate clients to pype 3.0, we'll need a quick way of promoting old studio presets to the new settings format.

Ideally this should be done using the proposed patch system in #630

[cuID:PYPE-1183]

**Comment by iLLiCiTiT** [comment]
> Ideally this should be done using the proposed patch system

This will require some manual inputs. At least define paths to previous pype-config and studio overrides. The patch system is more "automated" patcher, at least from what I saw, or is there a way how to define these inputs?

**Comment by iLLiCiTiT** [comment]
## Pype 2 / Pype 3
How to deal with Pype 2/Pype 3 conversion? Like single root -> multi root? Convert all to multiroot with `"work"` root and update all representations in database?

### Do we expect studio will use both Pype 2 and Pype 3?
If old projects would stay on Pype 2 and Pype 3 will be used on newer projects how would we handle differences in code for Mongo DB storing and changes in ftrack hadled with ftrack event server (sync to avalon)?

**Comment by mkolar** [comment]
>  Like single root -> multi root? Convert all to multiroot with "work" root and update all representations in database?

Yes this would be ideal and it's pretty much the point of patches, to be able to update database or other settings to the new pype version. 

> If old projects would stay on Pype 2 and Pype 3 will be used on newer projects how would we handle differences in code for Mongo DB storing and changes in ftrack hadled with ftrack event server (sync to avalon)?

tricky...we have to consider how to best manage this. Maybe a good solution would be to clone avalon database at the point of upgrade, so we could point 2 and 3 to different databases until all 2.x project are finished. That way we could run two event servers without issues. We might just need to have different trigger attributes for the auto sync for 2 and 3

**Comment by iLLiCiTiT** [comment]
Notes moved from PR https://github.com/pypeclub/pype/pull/1129

## Potential changes in current settings
1.) we allow change mongo database and collection names where ftrack events are stored - do we want allow to change that?
2.) Ftrack additional paths are now without platform specification so works only for single platform
    - expanding with environment is not implemented and requires to set an environments
3.) in System settings **General** category we have "Additional Project Plugins Path"
    - in Pype 2 it was used to determine folder where are subfolders with project name's but I'm not sure if that make sence now?
    - what if we move "Additional Project Plugins Path" to project settings where would be possible to set multiple different paths which would give ability to set paths to plugins that are common for multiple projects
    - the value is not used now in code (at least from what I saw) so we should at least use the value from it and use as expected
    - **BTW how do we plan to send those additional plugins to artist?**
    - **How do we add ability to have settings for plugins that are not in pype?**
4.) remove `studio_soft` and keep it as optional environment variable in general environments (as it is less used than used)

**Comment by iLLiCiTiT** [comment]
3.) "Additional Project Plugins Path" will be moved to project settings where it will be multiplatform and multipath entity and won't work as in Pype 2

**Comment by iLLiCiTiT** [comment]
## Issues
- `presets["ftrack"]["sync_to_avalon"]["status_name_change"]` is not used but has ability to be set in both Pype 2 and 3
    - removed feature? (accidentally)

**Comment by mkolar** [comment]
this has been finished gradually and is now obsolete
