### ISSUE TITLE
Ftrack without autosync in Pype 3

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1128]
## Description
It would be great if autosync in Pype 3 won't matter on custom attribute but on settings.

## Pros
- less custom attributes
- everything defined in settings

## Cons
- first synchronization must happen manually because the project must exist in avalon project's database to be able apply settings on the project
- add action that would turn on/off auto sync (e.g. for people outside studio without pype ATM when it's needed)
    - that may be less intuitive?

## How it may work
1.) allow change of the value only if has access to ftrack module that can send synchronization request to running event server 
- not much stable solution as is not controlled by handlers themselves, connection issues, may not be successful (can only send event which triggers that but it's hard to receive result if it actually happened)

2.) cache of autosync on/off value for each project have to be cached
- it is handled by one event handler it can be handled by him
    - store to a specific file in temp dir where each autosync change would be stored so even restarting of processor won't
       cause loose of data
    - don't know the logic of tmp file life (e.g. on linux) we must be sure the file is "alive"
- since it is handled in ftrack event processor it can be also cached in main process of ftrack event server
    - this disables legacy event server for sync to avalon as main process in that case is process where event handler lives
    - also can be handled differently if is not executed with our last ftrack event server variant
    - this variant would require to rewrite communication logic between subprocesses of ftrack event server to easily pass these data (which is also required for another features like pause processor/storer)

**Comment by mkolar** [comment]
We have to keep one thing in mind. This is something that's often done by producers that don't necessarily have OpenPype installed on their machine and rely on ftrack web GUI only. We might need to create an ftrack action with form gui that would run on the event server and would allow changing some settings, without affecting ftrack attributes.

**Comment by mkolar** [comment]
> add action that would turn on/off auto sync (e.g. for people outside studio without pype ATM when it's needed)
that may be less intuitive?

that's what I'm worried about. Attribute is quite clear, but I'd say we should be syncing it to an equivalent attribute in setting and use that when deciding whether to sync or not. So the attributes would work the same way as all the others.
