### ISSUE TITLE
Subset manager shows deleted nodes

### ISSUE THREAD

**Issue by 64qam** [pypeclub/OpenPype#1191]
Created nodes are visible in the subset manager. However, when a node is deleted from node view the subset manager does not catch the changes and the node remains in the manager. 

![image (4)](https://user-images.githubusercontent.com/26925793/112474195-9673f480-8d6f-11eb-912f-14bf15e62cc6.png)

**Comment by kalisp** [comment]
Orphaned instances in metadata should be removed
