### ISSUE TITLE
Define terminal application

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1245]
## Description
Nuke application/s can't be launched with python directly but must be launched through a terminal (commandline on windows, gnome-terminal on linux, etc.). But they may differ on each platform...

[cuID:PYPE-1344]

**Comment by antirotor** [comment]
I suppose this is problem mainly on Linux where there is multiple choices for terminal emulator software. And problem is that with some of them, you cannot pass set environment to them. We already use hack for this in Harmony under MacOS where environment is dumped to file and loaded by newly launched terminal emulator, but that is not ideal as you will either dump whole environment or you must filter it somehow.

Maybe best way would be to run part of OpenPype in new terminal emulator process and make it set environments. There are some snippets of code around to detect terminal emulator in shell script, like:

```sh
container() {
    pid=$$
    while true; do
        pid=$(ps -h -o ppid -p $pid 2>/dev/null)
        case $(ps -h -o comm -p $pid 2>/dev/null) in
        (gnome-terminal) echo "Running in gnome terminal";return;;
        (xterm) echo "Running in xterm";return;;
        (rxvt) echo "Running in rxvt";return;;
        (python) if [ ! -z "$(ps -h -o args -p $pid 2>/dev/null | grep guake)" ]; then echo "Running in Guake"; return; fi ;;
        esac
        [[ $(echo $pid) == 1 ]] && break
    done
}
container
```
