### ISSUE TITLE
Blender: loading layouts published with Blender doesn't load Materials

### ISSUE THREAD

**Issue by simonebarbieri** [pypeclub/OpenPype#1314]
# Issue
In Blender, some of the materials aren't loaded when loading a layout published from Blender. 

**Layout**:
![image](https://user-images.githubusercontent.com/1087869/114425626-2bb91a80-9bb1-11eb-9a4c-3339e3810468.png)

**Loaded Layout**:
![image](https://user-images.githubusercontent.com/1087869/114425520-0e844c00-9bb1-11eb-997a-1593154c6720.png)

Some of the materials are broken, while others are linked correctly:
![image](https://user-images.githubusercontent.com/1087869/114425581-1f34c200-9bb1-11eb-90d1-a283409624e7.png)
![image](https://user-images.githubusercontent.com/1087869/114426074-98ccb000-9bb1-11eb-8fb6-52853c359563.png)

[cuID:PYPE-1208]

**Comment by mkolar** [comment]
@simonebarbieri is this still relevant after the production tweak in the past months?

**Comment by simonebarbieri** [comment]
@mkolar No, it should be fixed!
