### ISSUE TITLE
MacOs issues

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#1326]
## Problem

1) We need to add build location (place where `openpype_console` is to sys path.
2) There can be issue during build with multiple versions of the same file (`liblzma.dynlib`) for me being copied to the same directory). This is know bug in **cx_freeze** and is already fixed and merged - marcelotduarte/cx_Freeze#915 - but not released yet. In that case we need to add it to `pyproject.toml` as git dependency pointing to master head.
3) Igniter UI has wrong scale of fonts
4) When Igniter is creating OpenPype version from frozen code it will not include `repos` for some reason. Result is error like this when running OpenPype:

![image](https://user-images.githubusercontent.com/33513211/114620427-de6da380-9cab-11eb-9143-0274ec6e6520.png)

5) When module fails to import - like **OpenTimelineIO** - it will produce absolutely cryptic and misleading traceback:

![image](https://user-images.githubusercontent.com/33513211/114621505-11fcfd80-9cad-11eb-8293-5b9424905461.png)

6) Running from sources with `poetry run python start.py tray --debug` will still result in error:

![image](https://user-images.githubusercontent.com/33513211/114621676-47a1e680-9cad-11eb-956d-88d406c2f594.png)

It seems we are importing **avalon** but not having it in `sys.path`

All tested on macos catalina 10.15.

**Comment by mkolar** [comment]
Install doesn't work at all from build

**Comment by mkolar** [comment]
Actually from build it doesn't run `Install`, or `Run without Installation`

**Comment by mkolar** [comment]
ok so 
1.- sorted
2.- sorted
4.- sorted

PR coming soon
