### ISSUE TITLE
Add Site information to scene manager

### ISSUE THREAD

**Issue by mkolar** [pypeclub/OpenPype#1337]
To be able to easily solve unsynced data in existing scenes, artists need access to site information and download/upload actions in the scene manager

Considering it already deal directly with representations, it should be as simple ass adding the columns on the right side with the same information as in the loader. Right click on a representation should then give option to download and upload

![image](https://user-images.githubusercontent.com/3333008/114713924-e4a66300-9d31-11eb-8cb4-0b0635c08b60.png)

**Comment by kalisp** [comment]
Code by accident committed to https://github.com/pypeclub/avalon-core/pull/321 
Can create separate PR if necessary.
