### ISSUE TITLE
Nuke openpype3

### ISSUE THREAD

**Issue by jezscha** [pypeclub/OpenPype#1342]
**Describe the bug**
Strange root node knob line creation
and AvalonTab is still created

**Screenshots**
![image](https://user-images.githubusercontent.com/40640033/114740788-76ba6580-9d4a-11eb-9826-f2b87d9284b1.png)

**Comment by mkolar** [comment]
this looks related https://github.com/pypeclub/client/issues/61

**Comment by jezscha** [comment]
After thorough investigation this bug is unfixable. It is nuke bug https://support.foundry.com/hc/en-us/articles/360019770660. 

Unfortunately, we are not even able to erase those lines programmatically as they are invisible to API to get.
