### ISSUE TITLE
Validation on OpenPype start

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1451]
## Desctription
- add validations on start of OpenPype like FFmpeg or OIIO (executables existence), mongo permissions (can access settings, logging,..._)
- `openpype.lib` should not initialize loggers and other stuff related to mongo on initialization

[cuID:PYPE-1316]

**Comment by iLLiCiTiT** [comment]
Blocked by https://github.com/pypeclub/OpenPype/issues/1574.
- It must be possible to do validations before core is used which right now happens on `openpype.lib` import

**Comment by mkolar** [comment]
I reckon this should be re-thinked in v4 considering the inftrastructure changes. What do you think @iLLiCiTiT?

**Comment by iLLiCiTiT** [comment]
I agree. It will happen during reorganization and the validation of dependencies already happens.
