### ISSUE TITLE
Deadline submit attr concurent tasks

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#1465]
We are not supporting settings of `concurent tasks` at the moment but those would be beneficial as sometimes rendering of nuke or other apps with only one thread is not efficiently using hardware resources. 

In nuke write node at Deadline Tab we will add `Amount of Concurent Tasks` knob which will be set by default to 1. Settings will be also defined. In case settings will be defined to 10 and user will not change render node knob to anything, settings will be used. If user change nuke write knob to anything other then 1 then value for submission will be taken from here instead of openpype settings.

[cuID:PYPE-1211]

**Comment by tokejepsen** [comment]
Could this not use the same workflow as the other Deadline settings which can be validated with the knobs validator?
