### ISSUE TITLE
Settings GUI navigation

### ISSUE THREAD

**Issue by mkolar** [pypeclub/OpenPype#1521]
As the settings grow it would be useful to be able to get and set a path to a particular place in settings using a simple path. All our settings are hierarchical like a folder structure, so we should be able to show a path to a currently focused item in form of 

`settings/system/modules/avalon/avalon_mongo_timeout`
`settings/projects/default/maya/publish/validate_shader_name`
etc.

Ideally, this path should be easily retrievable via right-click, and possibly by copying a path, as it is done in the file browser.

In the same fashion user should be able to enter the path, hit enter and be taken to that particular place.

When we then use these standardised paths in documentation and support tickets with clients it will make all the configuration support a lot simpler. 

[cuID:PYPE-1321]

**Comment by mkolar** [comment]
This would require two things to happens. 

- [ ] add editable path/breadcrumbs on top of the gui
- [ ] make it possible to click on an item, which would make it 'active` (active state can later also be used for displaying documentation in place.)

**Comment by jezscha** [comment]
or we could be able to click on any attribute key and in context menu select `copy path`

**Comment by mkolar** [comment]
>or we could be able to click on any attribute key and in context menu select copy path

I believe that is exactly what I meant by this. 

>Ideally, this path should be easily retrievable via right-click, and possibly by copying a path, as it is done in the file browser.

**Comment by iLLiCiTiT** [comment]
Resolved with https://github.com/pypeclub/OpenPype/pull/1932
