### ISSUE TITLE
Asset switcher choose loader

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#153]
Now it's not possible to define loader used for loading switched representations.
Related to issue https://github.com/getavalon/core/issues/377.

[cuID:PYPE-1377]

**Comment by iLLiCiTiT** [comment]
Not perfect implementation but it is working. 
![image](https://user-images.githubusercontent.com/43494761/82057026-1565be80-96c3-11ea-841e-8a76da0578e9.png)

**Comment by mkolar** [comment]
this duplicates #63
