### ISSUE TITLE
Subprocess Python 2/3 incompatibility

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#1544]
**Bug**
When running Python 3 as subprocess from Python 2 host it is possible to hit situation when there are modules in `PYTHONPATH` that breaks Python 3. We are now passing whole environment by default and that can include paths with
dangerous code. This is especially problematic with stuff in `site-package`, because there can be `.pth` files that contains
python code with imports and those are processed immediately when python is started.

**To Reproduce**
1. Create `site-packages` directory, install few modules inside and install *python futures* module (because that one directly throws exceptions when imported in python 3, so it is easier to see the problem).
2. Add it to some Python 2 host to `PYTHONPATH`
3. Run some python 3 subprocess from python 2 host - for example try to publish `Review` with *Extract burnin* plugin that is executing python 3 script

**Possible solution**
Possible solution would be to pass only "default" OpenPype environment if custom one is not explicitly specified. For example - we know that OpenPype needs `path/A` and `path/B` in `PYTHONPATH` so it should pass to subprocess only those.

[cuID:PYPE-1322]

**Comment by iLLiCiTiT** [comment]
I think in most of cases when we need to run Python 3 form Python 2 host is when we want run OpenPype, so we can not pass PYTHONPATH in those cases at all. It happens only during publishing, or?

**Comment by antirotor** [comment]
It can happen anytime as by default we are passing whole environment. But in this current case it happened during publishing in Extract burnin while running that OTIO script. We should state it in subprocess docstring that this can be used only to run OpenPype parts (at your risk in another words :)). And probably pop out PYTHONPATH from environment nevertheless.

**Comment by iLLiCiTiT** [comment]
> And probably pop out PYTHONPATH from environment nevertheless.

Well yes, but only place where OpenPype (python) subprocess is used like that is with otio script and Deadline plugin (where it is already solved).

So "fix" should be to change function `run_subprocess` in `~/openpype/lib/execute.py`.

Change line `env = kwargs.get("env") or os.environ` into:
```
env = kwargs.get("env")
if env is None:
    env = os.environ
```

...and documentation information (somewhere?) that it is not recommended as dependencies from source process may break new OpenPype process on start.

**Comment by antirotor** [comment]
Closing as this was edge case until it happens again :)
