### ISSUE TITLE
Nuke: Rendered Frame validation is triggered by multiple collections

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#156]
## Problem

rendered frame validator is now checking if files are rendered correctly by using `clique.assembly()` and failing when there are more collections then expected. But those other collections are of no importance now as we are working with explicit list of files and sometimes Deadline (or other software) is leaving behind *.tmp* files or other garbage that should not trigger this validator as it is safely ignored (or should be).

https://github.com/pypeclub/pype/blob/64da0039538139a3149956a82d6c1b928427f42e/pype/plugins/nuke/publish/validate_rendered_frames.py#L47

**Comment by antirotor** [comment]
Relates to pypeclub/pype#170

**Comment by mkolar** [comment]
temporarily fixed during 3.0 development. will be resolved fully when reworking integrator
