### ISSUE TITLE
Ftrack sync can't handle recreated entity in different hierarchy

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1563]
## Description
First of all I didn't test it all this is just hypothesis. Happened after conversion from 2.11.8 - 2.17.3 maybe happened because of the huge step inbetween or bug was already fixed in past.

Seems like sync to avalon can't handle if asset is `archived_asset`, recreated in different hierarchy with same MongoID in Ftrack Custom attribute and synced back.

### How to replicate (maybe)
- create entity in ftrack
- sync to avalon
- delete entity using `Delete Asset/Subsets` action
- sync to avalon
- recreate entity under different parent
- sync to avalon

### Missing pieces
- how MongoID from deleted(archived) asset got to new entity in ftrack?

### Result
- sync to avalon is trying to create new document with same MongoID like already existing document which cause conflict of `_id` key

[cuID:PYPE-1320]

**Comment by iLLiCiTiT** [comment]
Seems like the issue happened because `Delete Asset/Subsets` action didn't delete Ftrack entities so their custom attribute values were not removed.

**Comment by mkolar** [comment]
We've since re-written the delete action multiple times and I don't think we've hit this in v3. I'm closing this as hypothetical.
