### ISSUE TITLE
Mac application launch

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1575]
## Description
Applications in OpenPype can't be launched easily, it seems that possible solution is to set full path to executable.

One possible solution would be to add `open -a` before executables.

**Comment by antirotor** [comment]
This should use probably `open -an` (`-n` stands for open new instance of application even if one is currently running).

**Comment by iLLiCiTiT** [comment]
> This should use probably open -an

Cool, can that be used on any executable on Mac (Can I add it before any application launch)?

**Comment by antirotor** [comment]
well I am not sure but I don't think so. I think it can be used only on so called "application bundle" - but that should always end with `.app`, like `/Applications/Maya.app`.
