### ISSUE TITLE
Ftrack login server can't work without stderr

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1576]
## Description
It seems like `html.parse` is missing on MacOs build or maybe other python library required for Ftrack auto user credentials.

**Comment by antirotor** [comment]
this must be something different because all standard python modules should be included in freeze...

**Comment by iLLiCiTiT** [comment]
Was found out that issue is caused by using `sys.stderr.write` inside server listening for result.
