### ISSUE TITLE
OpenPype specific version issues

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1583]
## Description
Arguments `--use-version` and `--use-staging` work for just executed OpenPype process but it is not possible to execute children processes with same version.

### When it's problem
- ftrack event server (in both tray and studio service)
- all scripts executed from host (e.g. burnin script)
- all hosts using python (OpenPype) process before running real application (Harmony, Photoshop, AfterEffects and TVPaint)
- ...

**Comment by antirotor** [comment]
I suppose this could be solved by using `OPENPYPE_VERSION` that is already set. So if this exists, then it should constrain version to set there.
