### ISSUE TITLE
Delete/Calculate Old Versions cancel

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/OpenPype#1647]
**Describe the bug**
Reported by @BigRoy on Discord.

In the Library Loader on a Subset when clicing "Calculate Old Versions" on the option box and then pressing Cancel STILL shows a popup with the size.

**Expected behavior**
Dont show popup on cancel.

**Comment by kalisp** [comment]
I think that was fixed with https://github.com/pypeclub/avalon-core/pull/346

**Comment by kalisp** [comment]
Should be fixed by https://github.com/pypeclub/avalon-core/pull/346/files#diff-657d23f15ec9e63b3877669b575e43a9e4532a6ef82b2a6633e77e1c3b67c756R1352

(Please reopen if not.)
