### ISSUE TITLE
Hiero: creator instance error

### ISSUE THREAD

**Issue by 64qam** [pypeclub/OpenPype#1688]
After a regular publishable clip creation and clicking on Create button again, this error pop up. 

![image](https://user-images.githubusercontent.com/26925793/121660390-82ed4580-caa3-11eb-9417-b6f55537bf65.png)

**Comment by jezscha** [comment]
@iLLiCiTiT have you any idea what could be the problem? to replicate just:

1. go to Hiero
2. select clip in timeline
3. hit Create in OpenPype menu
4. create publishable clip and confirm
5. then hit Create on the same create family (haha there is only one)
6. this dialogue should show to you too

**Comment by iLLiCiTiT** [comment]
> @iLLiCiTiT have you any idea what could be the problem?

Will examine...

**Comment by iLLiCiTiT** [comment]
So. It's because you're modifying object attributes inside `process`.

You have to modify it to
```
def process(self):
    # get key pares from presets and match it on ui inputs
    presets = copy.deepcopy(self.presets)
    gui_inputs = copy.deepcopy(self.gui_inputs)
    for k, v in gui_inputs.items():
        if v["type"] in ("dict", "section"):
            # nested dictionary (only one level allowed
            # for sections and dict)
            for _k, _v in v["value"].items():
                if presets.get(_k):
                    gui_inputs[k][
                        "value"][_k]["value"] = presets[_k]
        if presets.get(k):
            gui_inputs[k]["value"] = presets[k]
        ...
```

And also add `import copy` at the top.
