### ISSUE TITLE
create virtualenv in Pype 3.0.0 using ./tools/create_env.sh will fail

### ISSUE THREAD

**Issue by Kaiz3rTool** [pypeclub/OpenPype#1693]
**Describe the bug**
create openPype virtual environment won't work using the recommended method in doc

**To Reproduce**
Following this step : https://openpype.io/docs/dev_build#to-build-pype
using ./tools/create_env.sh will fail and return : 
 
`
>>> Using python >>> Reading Poetry ... NOT FOUND
>>> Installing Poetry ...
Retrieving Poetry metadata

This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/Pype/OpenPype/./.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile files located at:

$HOME/.profile
$HOME/.bash_profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.1.6
  - Downloading poetry-1.1.6-linux.tar.gz (72.00MB)

Poetry (1.1.6) is installed now. Great!

To get started you need Poetry's bin directory (/Pype/OpenPype/./.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run `source /Pype/OpenPype/./.poetry/env`

>>> Updating dependencies ...
The currently activated Python version 3.6.8 is not supported by the project (3.7.*).
Trying to find and use a compatible version.
Using python3.7 (3.7.9)
Creating virtualenv openpype in /Pype/OpenPype/.venv
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  SolverProblemError

  Because openpype depends on slack-sdk (^3.6.0) which doesn't match any versions, version solving failed.

  at .poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
!!! Poetry environment installation failed
`

 - OS: Centos 7.8

**Comment by antirotor** [comment]
Thanks for the bug report - this is fixed by #1697 but fast workaround is to just run `poetry update`.
