### ISSUE TITLE
Validator plugins fine control

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#1704]
## Problem

right now some plugins (like validators) group together multiple check that make sense, like validating instance content, etc. But sometimes studio needs to disable one check and leave others on. Right now the only solution is to split this validator in multiple and control their execution via Settings/Presets. But this is cumbersome and needs to touch up code.

## Proposal
Add flags that will control execution of those checks inside plugin. That way only one control can be added to Settings/Presets.

For example:

**current state:**
```
check1()
check2()
```

**proposal:**
```
# meta code
if TEST_CHECK1 in PLUGIN_FLAGS:
    check1()
if TEST_CHECK2 in PLUGIN_FLAGS:
    check2()
```

related to #1654

[cuID:PYPE-1337]

**Comment by mkolar** [comment]
depends on #1639

**Comment by mkolar** [comment]
@antirotor I'm closing this ticket as not specific enough. If we need to separate out individual bits that we know of, lets make those into their own issues. This is now supported in the new publisher, so once that is ported to maya it's really just busywork of splitting them all up
