### ISSUE TITLE
Hiero: Scene inventory crash during version update

### ISSUE THREAD

**Issue by 64qam** [pypeclub/OpenPype#1718]
When trying to switch among the version in Scene inventory, the inventory crashes. It is usually happening on a version with a higher number of versions and during the downgrading. When you switch the version on an asset with just two versions, it is usually stable and nothing happens. 

![image (10)](https://user-images.githubusercontent.com/26925793/122232875-def90500-cebb-11eb-9331-ec9cab56f468.png)

**Comment by jezscha** [comment]
@pypeclient

After investigation this is a problem of Hiero and its very sensitive mp4 h264 ffmpeg wrapper. There are two ways to solve the issue:

1. not to use mp4 for loading and updating, instead use image sequence like the png
2. in case you'd rather prefare video files we would need to create another preset for publishing mov with prores422 -  those should be fine.
