### ISSUE TITLE
Switch all hardcoded additions of 'ftrack' to profiles based Settings

### ISSUE THREAD

**Issue by kalisp** [pypeclub/OpenPype#1729]
Currently to upload reviews to Ftrack 'ftrack' is added to instance's 'families' in each of the plugins by hardcoding.

After #1708 is merged, new more Settings based could be used instead.

This should be umbrella issue to collect all hosts which need to be updated:
- [x] AfterEffects
- [ ] Celaction
- [ ] Fusion
- [ ] Harmony
- [ ] Maya
- [ ] Nuke
- [ ] Photoshop
- [x] TVPaint (PR https://github.com/pypeclub/OpenPype/pull/1755/files)

[cuID:PYPE-1293]

**Comment by mkolar** [comment]
this has been implemented already
