### ISSUE TITLE
Client: slate generator refactory

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#1832]
- [ ] review code and update it to open Pype.club
- [ ] implement to Settings
- [ ] support thumbnail after review and burning
- [ ] support slate per representation 
- [ ] support PSD template

linked to https://github.com/pypeclub/client/issues/119 slate part

[cuID:yjx9ez]

**Comment by jezscha** [comment]
related pr https://github.com/pypeclub/OpenPype/pull/26
