### ISSUE TITLE
Settings: checkbox on Centos 7 almost invisible

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#1874]
This checkbox on Centos 7 is almost invisible, see screenshot:

![image](https://user-images.githubusercontent.com/33513211/127337100-b43b27db-7338-4745-9149-8428ec685c73.png)

[cuID:PYPE-1279]

**Comment by mkolar** [comment]
I'm going to close this now as it will be moved to web GUi in v4.
