### ISSUE TITLE
Settings: Initial settings of ftrack url

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#1875]
### Problem

on completely clean database, Centos 7:

1) run `./tools/run_settings.sh`
2) fill in ftrack url

On save, I've got:
![image](https://user-images.githubusercontent.com/33513211/127341606-231bd5e7-360a-48b3-b1bb-617121f0f844.png)

and in console:

```
>>> loading environments ...
  - for Avalon ...
  - global OpenPype ...
  - for modules ...
*** OpenPype [ 3.3.0-nightly.5 ] -----------------------------------------------
>>> Using OpenPype from [  /home/annatar/3.0  ]
... OpenPype variant:             [  production  ]
... Running OpenPype from:        [  /home/annatar/3.0  ]
... Using mongodb:                [  localhost  ]
... Using Deadline webservice at: [  http://localhost:8082  ]
... Logging to MongoDB:           [  localhost  ]
...   - port:                     [  27017  ]
...   - database:                 [  openpype  ]
...   - collection:               [  logs  ]
...   - user:                     [  <N/A>  ]
*** WRN: >>> { DictImmutableKeysEntity }: [  project_settings/unreal/project_setup Unknown keys in default values: "install_unreal_python_engine"  ] 
*** WRN: >>> { ftrack }: [  Couldn't create ftrack session.  ] 
==============================
Required "api_key" not specified. Pass as argument or set in environment variable FTRACK_API_KEY.
==============================
Traceback (most recent call last):
  File "/home/annatar/3.0/openpype/modules/ftrack/ftrack_module.py", line 145, in on_system_settings_save
    session = self.create_ftrack_session()
  File "/home/annatar/3.0/openpype/modules/ftrack/ftrack_module.py", line 353, in create_ftrack_session
    return ftrack_api.Session(**session_kwargs)
  File "/home/annatar/3.0/.venv/lib/python3.7/site-packages/ftrack_api/session.py", line 184, in __init__
    'Required "api_key" not specified. Pass as argument or set in '
TypeERROR: Required "api_key" not specified. Pass as argument or set in environment variable FTRACK_API_KEY.
```

It looks like it is trying to use `FTRACK_API_KEY` immediately even if it hasn't had a chance to be set. But the URL is set correctly:

![image](https://user-images.githubusercontent.com/33513211/127343565-f7f90828-755b-4489-afa2-08a899f8806e.png)

[cuID:PYPE-1284]

**Comment by mkolar** [comment]
I believe this was because ftrack was turned on by default, even before we had chance to set it up. @iLLiCiTiT I don't think this is an issue anymore, what's your take on it?

**Comment by iLLiCiTiT** [comment]
> I don't think this is an issue anymore, what's your take on it?

It still happens if you enable ftrack and set url for the first time. But I don't think it's an issue, or is it? It just tells that ftrack module can't update ftrack with settings values because url was changed (or user does not have filled ftrack api key).

**Comment by mkolar** [comment]
I agree. the message is quite clear as well I think. You just need to restart and all is good. I'll close this.
