### ISSUE TITLE
Loader: Asset refresh bug

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#1878]
### Problem

When loading something in Maya from the loader - and if that process takes long, then  when I select another asset in it subset list won't refresh. This is problem with productions where every asset has similar subsets so artist wouldn't notice until it's too late and he's working with wrong data.

![loader_refresh_problem](https://user-images.githubusercontent.com/33513211/127361946-d13a7723-0c06-4a04-b054-0d00cbb9d07e.gif)

### To reproduce:

Start Maya, open Loader and load as reference something (ideally bigger, so that operation take some time. Right after, click on different asset on right panel and subset list won't refresh. This is directly connected with time it takes to process it in Maya. With simple data that takes a moment to load it doesn't happen. As Maya is slow just after it started that is good moment to replicate.

[cuID:PYPE-1286]

**Comment by antirotor** [comment]
Duplicate of #196

**Comment by iLLiCiTiT** [comment]
Can't fix this in a way that the asset change would propagate without rewriting loader. But I can maybe add shadow overlay during loading so you can't click on different asset...
