### ISSUE TITLE
Global Increment Workfile plugin.

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/OpenPype#1883]
With each hosts workfile saving managed by the abstracted `workio.py` module, we could have one plugin to handle the workfile version incrementation for all hosts.

[cuID:PYPE-1288]

**Comment by antirotor** [comment]
Some hosts don't even allow to increment version of workfile (Unreal, ...) and it is probably better to leave it to them. We are closing it now but further discussion is welcome.
