### ISSUE TITLE
Asset parents validator should not be with project name

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#1918]
# Problem
Project name should not be part of instance data parents list. This apply on Hiero and standalone editorial publishing. 

this issue was temporarly addressed in this PR https://github.com/pypeclub/OpenPype/pull/1917 but it was more workaround then systematic solution. 

[cuID:PYPE-1245]

**Comment by mkolar** [comment]
resolved by https://github.com/pypeclub/OpenPype/commit/52f4a877cfcb227fb287f64a16d0578d88c6718b
