### ISSUE TITLE
TVPaint: Creator gets stuck behind renaming dialogue.

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/OpenPype#1953]
**Describe the bug**
When having the renaming dialogue open in TVP the Creator gets unresponsive.

**To Reproduce**
1. Open the Creator
2. Double click on a layer name to get the renaming dialogue.
3. While keeping the renaming dialogue open, try to create a render pass.

[cuID:PYPE-1259]

**Comment by mkolar** [comment]
this is not really possible to solve so we're closing it
