### ISSUE TITLE
Webpublisher: Subset name templates

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1969]
## Description
Webpublisher has defined subset name templates in different place than other hosts (`project_settings/global/tools/creator/subset_name_profiles`). Reason is that current subset template profiles don't use task type as filtering option.

## Suggested solution
- we should modify the filtering in `project_settings/global/tools/creator/subset_name_profiles` to be able use task types
- then remove subset template names from webpublisher settings to unify it

[cuID:PYPE-1464]

**Comment by mkolar** [comment]
I believe this is no longer a problem @iLLiCiTiT can you please confirm and close this if it's the case?

**Comment by iLLiCiTiT** [comment]
Yes, it is not an issue anymore.
