### ISSUE TITLE
Moving project folder structure creation out of ftrack module

### ISSUE THREAD

**Issue by icyvapor** [pypeclub/OpenPype#1989]
### Issue

Current Project Manager can create a new project, and add children hierarchy/assets/tasks. Then it relies on Workfiles module to actually create the specific work folders. 

Seeing the "project folder structure" settings under global config, we'd like OpenPype system to create the pre-configured project folders at the time of project creation.  

This functionality currently is embedded in a Ftrack specific action.  We'd like to have Project Manager trigger this functionality as well, so I'm proposing to move it out of ftrack module and into OpenPype API ? 

[cuID:11m56jn]

**Comment by tokejepsen** [comment]
This sounds great! I would add that it would be good to either have it as a setting to auto create or some right click action in th project manager.

**Comment by mkolar** [comment]
I absolutely agree It's actually somewhat related to this #1816 and it's really like this just because we didn't get to it yet.

@iLLiCiTiT any though or gotchas on this? I believe you had the deepest dive into this before.

**Comment by iLLiCiTiT** [comment]
> @iLLiCiTiT any though or gotchas on this?

100% Split those 2 logics. Create project hierarchy and folder structure should be 2 separated actions since we've added multiroots and logic to templates and since this change.

Actions should not definitely be "Auto executed" on project creation but should be possible to do so. That's because you may want change roots or templates or other related settings before folder creation is triggered and you may not want to create default project hierarchy.

Maybe I would do 2 ways how to trigger them:
1. Launcher actions that could trigger that.
2. Add 2 checkboxes for each action to project creation dialog?

**Comment by icyvapor** [comment]
Thanks for all the inputs. 

> 100% Split those 2 logics. Create project hierarchy and folder structure should be 2 separated actions since we've added multiroots and logic to templates and since this change.

I'm not quite clear about the concept of "project hierarchy". Is it a ftrack concept? 
Currently my intention is to factor out any logic that's not ftrack-related out of `openpype/modules/ftrack/event_handlers_user/*`.


> Actions should not definitely be "Auto executed" on project creation but should be possible to do it after creation in project manager. That's because you may want change roots or templates or other related settings before folder creation is triggered and you may not want to create default project hierarchy.

That's a good call. The physical folder creation will need to be an explicit user action, with confirmation probably. 

> Maybe I would do 2 ways how to trigger them:
> 
> 1. Launcher actions that could trigger that.
> 2. Add 2 checkboxes for each action to project creation dialog?

My understanding so far is, the Ftrack users won't ever touch the "Project Manager", and vise versa. So I'll probably focusing on enabling the folder creation in the Project Manager UI?

**Comment by icyvapor** [comment]
Now i'm a bit more confused: Why there's both OS folder creation logic in `openpype/modules/ftrack/event_handlers_user/action_create_project_strcture.py` and `~/action_create_folders.py`? And one is not referencing the other..

**Comment by mkolar** [comment]
There are two levels of creating project folder:

1. what we call folder structure (not super clear I realise, historical names that need more though), is simply a project kickoff that creates pre-defined folders which can be absolutely anything at all. Often production folder, downloads and various things that won't later be manage by a pipeline. This is there to replace common approach where a studio has one massive `example project` folder with tons of empty folders which they simply copy for each new project. 

2. `action_create_folders.py` is a contextual action that user can later run on any entity, shot, asset, task, you name it. and it will generate all of the folders for that particular entity before the work on it starts. OpenPype normally generates these on the fly as needed, however sometimes you need a shot folder way before any work commences, simply to drop in references for example.

**Comment by mkolar** [comment]
>My understanding so far is, the Ftrack users won't ever touch the "Project Manager", and vise versa. So I'll probably focusing on enabling the folder creation in the Project Manager UI?

That's correct. Right now PM tool is there to help those that don't have ftrack and we don't have a 2 way sync.

**Comment by iLLiCiTiT** [comment]
> My understanding so far is, the Ftrack users won't ever touch the "Project Manager", and vise versa. So I'll probably focusing on enabling the folder creation in the Project Manager UI?

I meant action in Launcher tool. Launcher may have different actions then application launch.

**Comment by icyvapor** [comment]
> There are two levels of creating project folder:
> 
> 1. what we call folder structure (not super clear I realise, historical names that need more though), is simply a project kickoff that creates pre-defined folders which can be absolutely anything at all. Often production folder, downloads and various things that won't later be manage by a pipeline. This is there to replace common approach where a studio has one massive `example project` folder with tons of empty folders which they simply copy for each new project.

Yep, this is what we were looking for. And I'm adding a button to trigger this in the PM UI.

> 2. `action_create_folders.py` is a contextual action that user can later run on any entity, shot, asset, task, you name it. and it will generate all of the folders for that particular entity before the work on it starts. OpenPype normally generates these on the fly as needed, however sometimes you need a shot folder way before any work commences, simply to drop in references for example.

Got it. I guess it's more related to Ftrack procedures. Thanks for the clarification!
