### ISSUE TITLE
Premium Addons Settings organisation

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#1991]
**Is your feature request related to a problem? Please describe.**
At the moment in MVP stage of implementation any added addon's settings is displayed in `project_settings` root. Also in `openpype\settings\entities\schemas\projects_schema\schema_main.json` the dynamic_schema is defined as `project_settings/global` and premium addon's settings are agregated under this key, this is quite confusing as the **global** key is used as hierarchical parent for global OpenPype settings.

**Describe the solution you'd like**
I believe it would be great to somehow distinguish premium addon settings from others - since those settings could be loaded to any already created hierarchical parents. Question is if we will need some addon's settings which are only addon related. Are we going to create some section? Something like `project_settings/addons`?

[cuID:PYPE-1811]

**Comment by mkolar** [comment]
This is being solved by the new settings implementation in v4, so it can be closed.
