### ISSUE TITLE
Experimental switch

### ISSUE THREAD

**Issue by mkolar** [pypeclub/OpenPype#20]
## Problem
Quite often we need to add a new large feature for a particular client that needs to be battle tested a bit before it can be released into production to everyone else. We need a way to include a feature and easily turn it on and off via config.

## Proposal

The easy and obvious way is using environment variable (`PYPE_EARLY_ADOPTER` to match Avalon maybe?) which we can read and switch accordingly in the code, however, that doesn't feel robust enough as some of these features will be scattered across the codebase or we might need to turn off some plugins completely to disable them.

On the other hand env var is simple and straightforward. 

## Considerations

Places where this would have to be put into effect are 

- Disable whole plugins
- Disable chunks of code
- Switch between old and new variant of the feature
- Switch between config variants possibly

[cuID:PYPE-1371]

**Comment by BigRoy** [comment]
The easiest and best case would to always see in which ways these features themselves could somehow be done as "Plugins" that can just be enabled or disabled. Of course, many changes won't allow that - nevertheless it would be good to keep an eye out on how to potentially we can get most things working well in a way that we can just consider it an add-on or plug-in.

An early adopter toggle worked well before, but it's also one of those things that just remains there and gets forgotten about at one point. Or even, then *all* features end up behind that wall making it lose it's usefulness.

If it's specific features, then maybe `PYPE_FEATUREX_ENABLE` could work well, where feature x of course is a short and simple name for whatever you're toggling.

**Comment by mkolar** [comment]
> then maybe PYPE_FEATUREX_ENABLE could work well, 

that's actually pretty good. 

Adding these things as plugins is usually impossible or restrictively complicated. #11 is a good example of a feature that we need to deploy to one client, but probably keep away from others until it's a bit production tested on smaller productions. That thing however touches code in pype, pype-config, pype-setup and avalon-core....
