### ISSUE TITLE
Build and zip version displayed on Ftrack

### ISSUE THREAD

**Issue by 64qam** [pypeclub/OpenPype#2002]
It would be nice if a zip and build version will be displayed in Ftrack Event server menu. It'll give us a quick overview of the current version. 

[cuID:11tyn6q]

**Comment by mkolar** [comment]
Which version there? If you're looking the the one that is running on your local machine, that it's accessible from the tray. Or it this so see ftrack event server version?

**Comment by jakubjezek001** [comment]
>  Or it this so see ftrack event server version?

Yes, I believe that is what @64qam had meant.

**Comment by 64qam** [comment]
Yes, sorry, ftrack event server version.

**Comment by iLLiCiTiT** [comment]
Closed by https://github.com/pypeclub/OpenPype/pull/2019
