### ISSUE TITLE
Ftrack delete action cause circular error

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#206]
## Issue
Ftrack action `Delete Asset/Subsets` may cause `CircularDependencyError`. Not sure why is this really happening.

## Theory: 
Deletion of entity will mark for deletion it's assets -> asset versions -> component and also it's tasks. If task is assigned to same assets as task's parent entity then maybe ftrack api will mark to unset task from that asset which may cause circular error because asset is marked to delete and change in one call. Seems like can be fixed with deletion of tasks first, to avoid this issue. Require testing...

## Traceback:
```
Traceback (most recent call last):
  File "K:\prod\pype-setup/repos/pype/pype/ftrack/actions\action_delete_asset.py", line 555, in launch
      self.session.commit()  File "K:\prod\pype-setup\vendor\python\ftrack-python-api\ftrack_api\session.py", line 1260, in commit
          result = self.call(batch)  File "K:\prod\pype-setup\vendor\python\ftrack-python-api\ftrack_api\session.py", line 1638, in call
              raise ftrack_api.exception.ServerError(error_message)ftrack_api.exception.ServerError: Server reported error: CircularDependencyError(Circular dependency detected. (DeleteState(<AssetVersion at 0x7f58f966c6d0>), DeleteState(<Task at 0x7f58f96d8590>), DeleteState(<FileComponent at 0x7f58f966c1d0>), DeleteState(<Asset at 0x7f58f96d8fd0>)))
```

**Comment by iLLiCiTiT** [comment]
Circular dependency error is still an issue.

### Note
Solution may be to delete all `Asset` entities of deleting entities first.

**Comment by jrsndl** [comment]
Hi,
not sure if it helps, but I can confirm I can successfully delete shot with task(s) and even published versions, if I run the Delete action "bottom first, one level at the time".  
1st: Select shot, delete, check only versions from the dialog, delete
2nd: Select shot, delete, check only tasks from the dialog, delete
3rd: Select shot, delete

It helped me many times already...
