### ISSUE TITLE
Nuke Studio crashes as a project is not set correctly

### ISSUE THREAD

**Issue by 64qam** [pypeclub/OpenPype#2089]
Nuke Studio crashes after the project loading because the project data in Ftrack (resolution height, width, FPS, etc.) are missing or not filled in properly. Nuke and Nuke X are fine.

[cuID:PYPE-1946]

**Comment by 64qam** [comment]
![image (20)](https://user-images.githubusercontent.com/26925793/135295880-7a7fdb72-2964-479f-a8db-d6d2a766d2df.png)

**Comment by mkolar** [comment]
@64qam do we know if this is still an issue?
