### ISSUE TITLE
Maya: Improve build workfile 

### ISSUE THREAD

**Issue by ClementHector** [pypeclub/OpenPype#2108]
## GOAL
We need to be able to create workfiles with an empty hierarchy or other objects that could be used to maximize the artist's working time.

## SOLUTION
Modify the build workfile to:
- be able to load a publish in the hierarchy
- be able to load a template

[cuID:PYPE-1971]

**Comment by mkolar** [comment]
Can you elaborate on what you mean by "load a publish in the hierarchy"? Do you mean being able to specify where a particular loaded model for example will appear in scene? Like within a group in maya outline?

This is actually closely related to a discussion here https://github.com/pypeclub/OpenPype/discussions/2013

And we've been looking at how to make templating possible for a while now. There is some brainstorming on the topic here as well https://miro.com/app/board/o9J_lazDzXA=/?invite_link_id=851891048526

I for one think, that implementing template file where you could "tag" certain nodes to be eventually replaced by loaded data, would allow for most flexibility.

**Comment by tokejepsen** [comment]
> And we've been looking at how to make templating possible for a while now. There is some brainstorming on the topic here as well https://miro.com/app/board/o9J_lazDzXA=/?invite_link_id=851891048526

@mkolar the miro board is password protected.

**Comment by ClementHector** [comment]
linked [PR](https://github.com/pypeclub/OpenPype/pull/2202)
