### ISSUE TITLE
Standalone publisher presets should be hardcoded

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#217]
Presets in pype-config for standalone publisher are not configurable at all.
## Extensions
- are for defying icons - that is not much project or even studio specific
## Families
- these seems to be presetable but in fact adding family doesn't mean it will be published as expected due to missing plugins for that
- not sure about families, please let me know

**Comment by mkolar** [comment]
this has been solve by settings in 3.0
