### ISSUE TITLE
Maya: Per scene custom environment variables

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#2215]
## Feature

It would be good to have ability to specify per scene file custom environment variables that will be passed to Deadline (or other) job. Those should be set on render instance and during job submition passed to render farm. One example of such environent is `MAYA_RENDER_SETUP_INCLUDE_ALL_LIGHTS` that is used to control lights in render setup.

[cuID:1r58a01]

**Comment by antirotor** [comment]
In fact, Deadline is bypassing `MAYA_RENDER_SETUP_INCLUDE_ALL_LIGHTS` in different manner, I'll open another issue for it. But nevertheless this feature is still relevant.

**Comment by BigRoy** [comment]
This issue sounds like it's less of a Maya issue but potentially just a general pipeline issue. What if we'd want to ingest extra environment variables for only a specific asset/shot, or even a specific task.

It could work like the new filtering used in `project_settings/global/tools/Workfiles/extra_folders` where extra env vars could get added in general for any host, for any task type, and potentially even with a filter to specific assets? :)

**Comment by antirotor** [comment]
I am afraid this needs to be set even on scene level. Say you need to change license server just for specific scene/render... I agree that this is in general pipeline issue and very hackish.  But as the render setup light issue is solved in different way, I'll close this one until we'll find some other case to rationalize time spent on it.
