### ISSUE TITLE
Version re-hashing

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#2216]
## Feature

We need to to re-create hashes in `checksums` so OpenPype version is properly validated when changes are made on code without the need of rebuilding.

### Description

Typically quick fixes include extracting zip file, making changes in few files, modifying `version.py` and re-computing sha256 hashes to `checksums` file list. Currently only way is to compute checksums manually (for example using Powershell) but it would be nice to have included script file that will bump version in `version.py` and refresh `checksums` to make it valid OpenPype version.

[cuID:OP-2000]

**Comment by jakubjezek001** [comment]
Also it would be awesome if you could simply disable temporarily the validation by evironment variable - lets say `OPENPYPE_CHECKSUM_VALIDATE_OFF`.

**Comment by jakubjezek001** [comment]
related issue https://github.com/pypeclub/OpenPype/issues/2240
