### ISSUE TITLE
Settings Copy/paste project settings to another project

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#2217]
**Is your feature request related to a problem? Please describe.**
At the moment we are able to copy settings' key values and paste it to another project at the same level. But it would be awesome to do the same on a Project level.

**Describe the solution you'd like**
RMB click to a project in the project list in Project settings section and use action name `Copy settings from another project`. A project select popup will appear and after a project is selected and confirmed all the settings will be synchronized.

**Describe alternatives you've considered**
In project settings go to project's list and RMB click to a project you want to copy from. use `Copy project settings`. Then RMB click to another project and use `Paste project settings`. That is one way to do this. 

**Additional context**
We have to identify a scope of coppied variables as some we dont want to copy - like project name/code or perhaps some values in Anatomy

[cuID:OP-2001]

**Comment by iLLiCiTiT** [comment]
Resolved with https://github.com/pypeclub/OpenPype/pull/2382
