### ISSUE TITLE
Checksum windows backslash breaking linux Igniter

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#2240]
**Describe the bug**
When zip is created on windows and added to linux versions, Igniter is returning error that `openpype\action.py` does not exists. It is caused by the fact that checksum is storing backslashes. 

this had appended on `openpype-3.6.0-nightly.2-centos.zip` build

**To Reproduce**
1. create zip on windows
2. add it to version repository in linux environment
3. open `openpype_console` in linux 
4. see there is an error with missing `openpype\action.py`

**Expected behavior**
It should load the version and open it. 

![image](https://user-images.githubusercontent.com/40640033/141497371-86c5c84f-eb21-49bf-a6c9-efd64e176c82.png)

[cuID:OP-2020]

**Comment by antirotor** [comment]
Related to #2216
