### ISSUE TITLE
Add path for bundled OpenImageIO by default

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#2351]
## Enhancement

We are depending on `oiio_tool` and `maketx` tools. We shoudl either add oiio to `PATH` or change code to look for it in `PATH` and if not found, use the one bundled (or vice versa?)

[cuID:1vx6tm5]

**Comment by iLLiCiTiT** [comment]
The same issue as with ffmpeg you never know if on the machine already is oiio tool in PATH that's why we have `get_oiio_tools_path` function in openpype lib.

**Comment by antirotor** [comment]
Superseded by #2386
