### ISSUE TITLE
Launcher [UI] + [DB] Improve launcher filters

### ISSUE THREAD

**Issue by victorbartel** [pypeclub/OpenPype#2380]
**Is your feature request related to a problem? Please describe.**
The launcher pop-in seems to lack filtering abilities. We are looking forward to being able to filter tasks within launcher form by assigned users, dates, status, etc. It might be crucial when your team counts a few dozens of artists.

**Describe the solution you'd like**
In the beginning, we need to have an additional drop-down box containing available usernames. On selection of one of the usernames, the launcher form should display tasks, assigned to the selected user only.

**Describe alternatives you've considered**
We don't have any alternative for the time being.

**Additional context**
The feature that we need remains impossible without changing the format of the data contained within Avalon database. We would suggest improving project tasks and extending existing task representation with followed format:

```json
{
  "tasks": {
    "color": {
      "type": "Design",
      "workingStatus": "STATUS",
      "dueDate": "2021-12-08T00:00:00",
      "assigned": [
        {
          "username": "user1",
          "assignedAt": "2021-12-01T00:00:00"
        }
      ]
    },
    ....
  }
}
```
We are ready to develop such a filtering feature if you agree to the proposed format. Likewise, we are keen to hear from you any proposal, if you have such. Please keep us posted, the time is of the essence in such matter. Many thanks.

[cuID:OP-2095]

**Comment by mkolar** [comment]
In general this is of course desirable. We just need to ensure backward db compatibility and have a look at planned data model for v4 it can be then easily converted once it's out (it's not 100% ready for wide discussion, but we're happy to do a deep dive with you.)

In general the data model you proposed as example should work perfectly well I think. @antirotor @iLLiCiTiT @martastain can get your 2 cents here please?

**Comment by victorbartel** [comment]
Hey @mkolar,
Thanks for coming back. I didn't speak about backward compatibility, but it was taken in consideration. The proposed format should not introduce any breaking change(but we count to test the thing). 

Maybe some of proposed fields may go under universal **data**, we don't have any particular opinion on the matter.

For v4, IMHO, it would be great to make tasks first class citizen of the project hierarchy. The other way around, the migration should work like a charm. 

We're going to start implementing this feature and will come back to you asap.

**Comment by iLLiCiTiT** [comment]
Few questions and notes:
1. Where to put the filtering fields?
    - should be visible if any task does not have those data filled (backwards compatibility)?
2. Assets and tasks widgets are now separated widgets (components) with it's own separated logic but with this tho whole launcher should have single model from which all it's components load data to avoid querying the same data 2-3 times. At least I expect you also want to filter assets if it's tasks do not contain entered filters...
3. Loading of all these data (all tasks for all assets) will slow down loading of the data from mongo (especially from cloud mongo) which may have huge impact for a bigger project so it would be maybe nice to have this advanced option toggleable and turned off by default.
4. I would change `workingStatus` to `status` or is there any other status that can be on task?

> For v4, IMHO, it would be great to make tasks first class citizen of the project hierarchy. The other way around, the migration should work like a charm.

I think the issue is that publishing must point to an asset (or a node in OP4) so task under project could not trigger any publishing not sure if that can change in OP4.

**Comment by mkolar** [comment]
>For v4, IMHO, it would be great to make tasks first class citizen of the project hierarchy. The other way around, the migration should work like a charm.

OP4 already has tasks in their own table so full-featured objects, with same options as assets mostly. 

I also wonder about the status field. We have status support in general as a ticket for OP4 so we should align on the namings for OP3 at least so that conversion later would be easy.

**Comment by mkolar** [comment]
Practically all project management systems I've come across use two levels of statuses. In OP3 I think sticking to simple string might server the purpose, but in OP4 we'll most probably opt for statuses that will have more attributes like type, colour and such.

**Comment by antirotor** [comment]
about the UI, I think pretty standard way of filtering stuff is like what's in ClickUp:
![image](https://user-images.githubusercontent.com/33513211/146002163-cf3eb8b4-3d77-4137-b8ac-85473fffbd01.png)
This allows to apply dynamic filters based on what is available.

**Comment by ClementHector** [comment]
I think it would be easier for users to have this kind of filter:
![image](https://user-images.githubusercontent.com/7068597/146004674-442b9919-afd5-40a8-baf0-0120a4803312.png)
Which opens to have the list of possibilities to check:
![image](https://user-images.githubusercontent.com/7068597/146005045-ceae8258-8def-4496-9f69-228900f2cd3f.png)

**Comment by ClementHector** [comment]
Maybe like this?
![image](https://user-images.githubusercontent.com/7068597/146008486-438a6bbd-8b79-4cde-b41f-388bb10ab823.png)
![image](https://user-images.githubusercontent.com/7068597/146013093-a6632755-7ab9-4dfc-90e7-ccd5654b448f.png)

**Comment by ClementHector** [comment]
Or like this?
![image](https://user-images.githubusercontent.com/7068597/146018634-82516436-0568-4dc5-8f8d-43b2e8638e48.png)

**Comment by antirotor** [comment]
I like the last one. This issue is related to #1787 but we've decided that Dashboard would be properly implemented in v4
