### ISSUE TITLE
Maya: extract look should use `maketx` from OpenPype OIIIO

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#2386]
## Problem

Extraction of look now depends on `maketx` tool presence in `PATH`. We shoud set it to use OpenPype's bundled OIIO version.

Related to #2351

[cuID:1wzqmx5]

**Comment by iLLiCiTiT** [comment]
you can use
```
from openpype.lib import get_oiio_tools_path

maketx_path = get_oiio_tools_path("maketx")
```
