### ISSUE TITLE
Blender 3: Workfiles tool cause crashe on save

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#2407]
## Description
Blender 3 crashes when workfiles tool is used for saving new workfile. Almost 100% time when Save as is used.

## Suggested solutions
1. Modify save method in blender host to do the save defferend in blender's main loop.
    - this will cause that files in workfiles tool won't be refreshed and newly create workfile won't be visible after confirmation of save
2. Rewrite blender implementation to not use PySide2 directly inside blender's loop but in serparated process

### Crash report
[blender.crash.txt](https://github.com/pypeclub/OpenPype/files/7712300/blender.crash.txt)

[cuID:OP-2172]

**Comment by mkolar** [comment]
fixed already
