### ISSUE TITLE
Settings UI: Deffered change of value can cause issues on save

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#2414]
## Description
Value changes from UI inputs are in some cases deffered to make UI smoother but it is possible to hit `Save` before the values are propagated in entity. In that case changes are not propagated and save may crash if the deffered change is removement of item (from list or dictionary).

[cuID:1xw4f45]

**Comment by mkolar** [comment]
I would close this, considering the switch to web stack for this.
