### ISSUE TITLE
Updating submodules will fail if tracking branch is missing

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#2427]
**Describe the bug**

During the build we are using `git submodule update --recursive --remote` to pull latest changes in submodules. But if remote is missing the branch that was used for the current HEAD, it will fail with:

```
fatal: Needed a single revision
Unable to find current origin/HEAD revision in submodule path '...'
```

Currently this is the case of **Arrow** submodule used in ftrack-api for python 2 that must be on tag 0.17 - latest py2 compatible version. But since then, they've deleted `master` and recreated it so 0.17 becomes detached.

Solution is to drop `--remote` from the command. But we'll then loose ability to pull the tracking branch, but that might not be an issue for us anyaway...

[cuID:OP-2215]

**Comment by mkolar** [comment]
we managed to get rid of all submodules, so I believe we can safely close this. @antirotor re-open it if you thin we need to solve it anyways for potential future issue.

**Comment by antirotor** [comment]
True but with addons in v4, we might still hit this. Sleep well issue, sleep well.... Until one day..
