### ISSUE TITLE
Maya Create Render Creator fails for Redshift

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#2446]
**Describe the bug**

_Maya + Redshift_

1. Set current renderer to Redshift in Maya 2020 or Maya 2022
2. Avalon > Create.. > Create Render

Results in this error:

![unknown](https://user-images.githubusercontent.com/2439881/147566079-6a7caf16-61a6-4aae-9404-32bc2648f4a7.png)

Source of issue is that the [`_set_renderer_option`](https://github.com/pypeclub/OpenPype/blob/dd0e3657b4e66740f55feddb2693acfd14e2c9ef/openpype/hosts/maya/plugins/create/create_render.py#L458-L460) method does not exist on the CreateRender object. 

It was originally added in [this commit](https://github.com/pypeclub/OpenPype/commit/a8bf58142e8f61fb1cb4e9cc2fd62465bae8a47f#diff-c2d142bd9f2f12448c298b5d18bd55681c6dac438481c2f953174549da200043). It was removed in [this commit](https://github.com/pypeclub/OpenPype/commit/d4088931662a5683c9606fe019717fb85dc31395), see [here](https://github.com/pypeclub/OpenPype/commit/d4088931662a5683c9606fe019717fb85dc31395#diff-c2d142bd9f2f12448c298b5d18bd55681c6dac438481c2f953174549da200043L449-L469)

**Questions**
@antirotor - Any particular reason this got removed? How would you like me to fix it?

We could either change it to:
```python
            cmds.setAttr("redshiftOptions.imageFormat", 1)  # EXR
```

Or add the `_set_renderer_option` back in for the different renderers.

---

Also, additionally I'd like to bring up a question. Are we sure we want this Creator to change up the render settings directly? What if the User had already prepped the scene for a bit before creating the Render instance?

[cuID:OP-2253]

**Comment by antirotor** [comment]
This is actually in process of refactoring (#2282) . Goal is to have these renderer settings in Settings UI and to be able to configure there what should be set by this creator and what not. I suppose that by default it will only force image formats and such things.
