### ISSUE TITLE
Maya 2022: Color Management default to new config OCIO with renamed color spaces and settings

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#2454]
### Issue

OpenPype's default Color Space settings for maya are set to:

- Rendering Space: `scene-linear Rec 709/sRGB`
- Viewer Transform: `sRGB gamma`

Both of these names do not exist with the default OCIO config in Maya 2022.
They are now named `scene-linear Rec.709-sRGB` and `sRGB`

As such the `set_colorspace` fails in Maya 2022 resulting in these errors on New File or Maya launch:
```python
Traceback (most recent call last):
#   File "S:\openpype\OpenPype\repos\avalon-core\avalon\pipeline.py", line 631, in emit
#     callback(*args)
#   File "S:\openpype\OpenPype\openpype\hosts\maya\api\__init__.py", line 206, in on_task_changed
#     lib.set_context_settings()
#   File "S:\openpype\OpenPype\openpype\hosts\maya\api\lib.py", line 1924, in set_context_settings
#     project_data.get(pixelAspect_key, 1))
#   File "S:\openpype\OpenPype\openpype\hosts\maya\api\lib.py", line 2825, in set_colorspace
# RuntimeERROR: colorManagementPrefs: Rendering space scene-linear Rec 709/sRGB is unknown.
# 
```

This is because Maya 2022 comes with a new `.ocio` config (default) and considers the old `.ocio` file legacy.

- Maya 2022 Default: `<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio`
- Maya 2022 Legacy: `<MAYA_RESOURCES>/OCIO-configs/Maya-legacy/config.ocio`

Also note that Maya 2022 completely revised settings for "View Transform". It now has two separate options **Display** and **View**. More details in the [Maya 2022 documentation on Color Management](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2022/ENU/Maya-Customizing/files/GUID-2D9BBB9D-49F0-44C6-8BFF-B237FD8ED746-htm.html)

### Potential solutions

We can maybe allow a comma/separator divided list of values to fall back to in the settings, e.g. `scene-linear Rec.709-sRGB;scene-linear Rec 709/sRGB`.

Or as @jakubjezek001 mentioned on discord maybe make the settings a combobox entry with a mapping per application version. But even those might be wrong when you are using a custom OCIO file.

> Example quoted from Discord
> ```
> [
>     {"rec_709_srgb": "Rec.709-sRGB"},
>     {"gamma22": "Gamma 2.2"}
> ]
> ``` 
>
> Mapping for Maya 2022 in code
> ```
> mapping_2022 = {
>     "rec_709_srgb": "scene-linear Rec.709-sRGB",
>     "gamma22": "..."
> }
> ```
> 
> Mapping for others in code
> ```
> mapping_old = {
>     "rec_709_srgb": "scene-linear Rec.709/sRGB",
>     "gamma22": "..."
> }
> ```

Another fix could be by always defaulting to an `.ocio` file that gets provided with OpenPype which we can keep consistent across maya versions.

### Discussion

It would be good to know what a preferred method of fixing this would be. 

Note that this could get extra complicated when mixing Maya 2020 + Maya 2022 in a single production - if you ever do that.

[cuID:OP-2260]

**Comment by BigRoy** [comment]
Looking at the difference between the legacy OCIO (v1) to the new OCIO (v2) options it might be better to actually separate the two like that in the Admin settings too.

We could have a toggle for choosing OCIO v2 over v1 when available or even have it choose legacy in Maya 2022 since it provides completely [new and different arguments for `maya.cmds.colorManagementPrefs`](https://help.autodesk.com/view/MAYAUL/2022/ENU/index.html?contextId=COMMANDSPYTHON-COLORMANAGEMENTPREFS) when either in v1 or v2.

**Comment by antirotor** [comment]
> As such we'd just have new extra settings for OCIO v2 (that are relevant to Maya 2022+) - Thoughts?

Yeah, I think that we should actually do both - provide default OCIO config with OpenPype (as it would even help anyone not really versed with color management to start using some sane default values) and have ability to choose between v1 and v2 OCIO in Maya 2022. I am not sure when will Autodesk deprecate v1 support, but we'll see.

**Comment by BigRoy** [comment]
This issue might related to the **colorspace distribution** [discussion](https://github.com/pypeclub/OpenPype/discussions/2574) and [issue](https://github.com/pypeclub/OpenPype/issues/2579).

**Comment by BigRoy** [comment]
![maya2022_ocio_settings](https://user-images.githubusercontent.com/2439881/150682422-12d49c27-80cc-4b96-ad3d-80b8c8f7cbc7.png)

@mkolar @antirotor Here's how it would look in settings. Thoughts?
Will look into implementing code coming week.

**Comment by BigRoy** [comment]
Actually I just found out that in Maya 2022 the `ociov2Enabled` flag isn't one you can set but it's only one you can query. It's because it basically depends on whether the used ocio config is OCIO 2+.

I am not sure how to best be explicit about this in the OpenPype settings currently. It would be great if someone at OP dev team could take a stab at this in a way that aligns with other approaches taken with OCIO (or at least steer me in the most logical direction for OpenPype to implement it.)

Would love to fix up this behavior to get the full Maya 2022 support merged soon.

**Comment by antirotor** [comment]
I think this is a part of much bigger issue with handling colors in OpenPype, but as we need to make Maya 2022 available asap, lets divide it and implement now "dumb but fast" solution. Lets do it like you have on the screenshot, but add logic to prelaunch hook to select what's appropriate for running Maya version...

Then with proper implementation, we can add OpenColorIO as library and use it's python api to parse available config files and make it more smart, better, nicer, shiny and whatnot,,,

**Comment by mkolar** [comment]
We had some more discussions today and looking at the mockup from settings here, I'd also say that it's the way to go for now. Especially considering it's not only the ocio config, but also the attributes in maya themselves that have changed.

**Comment by BigRoy** [comment]
The original Maya 2020 color settings. Can someone confirm for me did they what they intended to do? :) They don't seem to work for me on Maya launch (**_they do work on New File but not on Maya start_**). So the initial scene without open latest workfile, the empty scene Maya starts in, doesn't initialize to the right settings.

For example change Rendering Space to `ACEScg` and Viewer Transform to `1.8 gamma`. Maya 2020 will not start with those settings for me. @mkolar can you confirm on your end?

**Comment by BigRoy** [comment]
@mkolar I'd like to propose an alternative that looks more like how it's done for settings for Hiero and Nuke.

**Settings layout**

![afbeelding](https://user-images.githubusercontent.com/2439881/151124825-51c43d43-80ab-46cb-853f-ef85c0a07a86.png)

With the dropdown:
![afbeelding](https://user-images.githubusercontent.com/2439881/151124883-b65e4f54-91e0-4586-9658-e7a02d495076.png)

**View / View Transform*

The old color config basically uses "View Transform" which is basically View + Display but in the legacy styling Display was never explicitly set in preferences. So I'd say that we use a fallback for "View" that if we're in an older host (Maya pre 2020) or are using a legacy 1.0 config then we use the View value as View Transform.

I'll implement the code changes in a bit in another branch.

**Comment by BigRoy** [comment]
@mkolar Here is the new proposed code, [branch](https://github.com/BigRoy/OpenPype/tree/maya2020_ociov2_b) with [commit](https://github.com/BigRoy/OpenPype/commit/d3c790bdc207f42d7642e95302538aae402163b0). This is basically the [implementation as described in the comment above](https://github.com/pypeclub/OpenPype/issues/2454#issuecomment-1021954310) - I much prefer that code.

**Comment by BigRoy** [comment]
Any thoughts on the above? Is the latest approach I described the most sensible for now?

Once we pick I can merge and refactor to work with latest develop changes which merges Maya host from Avalon into OpenPype.
