### ISSUE TITLE
anatomy multiroot workfiles per task 

### ISSUE THREAD

**Issue by jezscha** [pypeclub/OpenPype#246]
**Is your feature request related to a problem? Please describe.**
Workfiles could be targeted to different root (multi-root) regarding a task. 

**Describe the solution you'd like**
New key in anatomy template file could be created with defined task group which it is dedicated to.

**Example**
```
work[conforming]:
  folder: "{root[production]}/{project[name]}/{hierarchy}/{asset}/work/{task}"
  file: "{project[code]}_{asset}_{task}_{@version}<_{comment}>.{ext}"
  path: "{@folder}/{@file}"
``` 
or

```
work[conforming, compositing]:
  folder: "{root[production]}/{project[name]}/{hierarchy}/{asset}/work/{task}"
  file: "{project[code]}_{asset}_{task}_{@version}<_{comment}>.{ext}"
  path: "{@folder}/{@file}"
```

[cuID:PYPE-1378]

**Comment by iLLiCiTiT** [comment]
I like this solution, but have few questions:
1.) Expect this is allowed only for `work` templates?
2.) Where task name pick should be handled?
    - I see 2 possibilities: avalon-core's lib or Anatomy
3.) How Configuration GUI will look like? (Don't expect result, just keep in mind it must be able to set it via gui)

**Comment by jezscha** [comment]
> I like this solution, but have few questions:
> 1.) Expect this is allowed only for `work` templates?

don't need to be only for `work` this could potentially by usable for any task. This way we would have total control over multi-root and defined storage permissions (this is the main reason from the client request)

> 2.) Where task name pick should be handled?
> - I see 2 possibilities: avalon-core's lib or Anatomy

Perhaps Anatomy would be good place to handle it from. What do you thing?

> 3.) How Configuration GUI will look like? (Don't expect result, just keep in mind it must be able to set it via gui)

Not really sure, we could brainstorm it in group ;) You know more about this topic then I do ;)

**Comment by iLLiCiTiT** [comment]
> This way we would have total control over multi-root

I see potential of breaking during publishing of editorial.

> Perhaps Anatomy would be good place to handle it from.

I don't see easy way how to get templates (unfilled) for specific task with one anatomy object.

> You know more about this topic

I know about Qt, not about how this may look. Templates design is not defined yet.

**Comment by jezscha** [comment]
> I see potential of breaking during publishing of editorial.

Could you elaborate on why do you thing it could break?

> I don't see easy way how to get templates (unfilled) for specific task with one anatomy object.

well if we had method for getting and filling only particular part of anatomy template then yes it would be possible.

**Comment by iLLiCiTiT** [comment]
> Could you elaborate on why do you thing it could break?

I think during editorial publishing are pre-published subsets for assets created during publishing. I don't know if it will break because I don't know how it works...

> filling only particular part of anatomy template

Again: I don't see __easy way__ how to get templates (__unfilled__) for specific task.
