### ISSUE TITLE
New publish plugin action DisplayAction

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#2474]
**Is your feature request related to a problem? Please describe.**
At the moment we are dealing with repair actions on instance or context level and those are defined in @classmethod in particular plugin. In some plugins for example in Nuke we want to help user to navigate within their complex node trees to see what node had failed. But we are not having abstraction for display action as we are having for repairing.

**Describe the solution you'd like**
New abstraction method could be created in openpype action for this. Labeled `Show instance` or `Display in workfile` or even shorter if possible.   

[cuID:1z9xfu9]

**Comment by BigRoy** [comment]
Would **Selecting** the nodes be enough? I assume it can be hard to "frame"/"display" the relevant nodes in Nuke automatically as they might be far apart or they might be inside groups/containers and thus still not be apparent? I assume once nodes are selected then the user can frame or do whatever they are accustomed to do in the host to find the relevant nodes.

Another approach would be to allow a little pop-up Qt list widget like UI that lists all invalid nodes where the user could select each individually. However - it seems more involved to produce and less familiar to the artist with the host/tool they are working in.

**Comment by jakubjezek001** [comment]
Hey @BigRoy, I am not sure how this would work in Maya or Houdini so I will talk only about Nuke.
Since this will be more related show user the failed Instance. This want shown on Context in multiple instances. 

Usually in the instance you are having only one node, but there are cases where for example whole backdrop full of nodes could be failing. Here we would frame in the node graph viewer only the whole backdrop node. So roughly if in the case of more failures, the user would need to display these one by one.

**Comment by antirotor** [comment]
I will close this as I think this is already working per host/plugin - like many Maya plugins are using action "Show Invalid" that is doing I think exactly this, so I believe this is per host per plugin, unless I am mistaken.
