### ISSUE TITLE
Error message in Loader is not on top

### ISSUE THREAD

**Issue by kalisp** [pypeclub/OpenPype#2487]
If error is thrown in the Loader, error message window is not pushed on top of the Loader (and is missing styling and icon).

It would be nice to make print of the stacktrace collapsible (or indented or lower or less prevalent).

(Same situation is probably in Creator.)

[cuID:1zfp052]

**Comment by BigRoy** [comment]
```python
import avalon.api

class CrashCreator(avalon.api.Creator):
    label = "Crash"
    family = "crash"
    
    def process(self):
        raise RuntimeError("Crash creator")
        
        

class CrashLoader(avalon.api.Loader):
    
    families = ["*"]
    representations = ["*"]
    label = "Crash"
    def load(self, context, name=None, namespace=None, options=None):
        raise RuntimeError("Crash loader")
    

avalon.api.register_plugin(avalon.api.Creator, CrashCreator)
avalon.api.register_plugin(avalon.api.Loader, CrashLoader)
```

I used this to register an erroring Creator and Loader.

In the Creator UI it shows the error on top fine with the right styling.
In the Loader UI it shows the error popup on top fine for me, however **without** the right styling.

What OS + Host is failing for you to raise the pop-up to the front?

**Comment by iLLiCiTiT** [comment]
> What OS + Host is failing for you to raise the pop-up to the front?

It does not work in hosts which are not Qt based or do not pass parent widget. In that case tools have flag "AlwaysOnTop" which cause that dialogs are  moved to back if parent is not passed.

**Comment by BigRoy** [comment]
> That would be also solved with passing the parent.

I was thinking so, yes.

Note that the [Creator error dialog explicitly styles itself during showEvent](https://github.com/pypeclub/OpenPype/blob/d8cada627f04182f00bdba6ce036af39414a27c2/openpype/tools/creator/widgets.py#L77) whereas the Loader error dialog does not. Might make sense to unify that behavior between the two either way.

> The real request in this case is the collapsible traceback.

❤️ - With a little "copy error report"?
