### ISSUE TITLE
Fusion: pre_fusion_setup.py errors formatted wrong in Launcher

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#2500]
**Describe the bug**

Any errors generated in `pre_fusion_setup.py` get shown up in the bottom bar in the Launcher, however the current code has very funny formatting due to backslashes and other symbols not being escaped.

![odd_error_message](https://user-images.githubusercontent.com/2439881/148553489-288436cd-433d-4f2f-9d12-6850bd914034.png)

[The source code that produces the error](https://github.com/pypeclub/OpenPype/blob/c00f9a98bd15db71a1cff22710828a453af608d9/openpype/hosts/fusion/hooks/pre_fusion_setup.py#L17-L21)

**To Reproduce**
1. Set an invalid path to Python 3 to ensure the error happens.
2. Run Fusion

**Expected behavior**

The error message should be nicely formatted.
Plus I'd also expect the error to result in a pop-up window similar to when an Application can't be found. Similar to this:

![afbeelding](https://user-images.githubusercontent.com/2439881/148553931-95caf3a6-7220-497c-b38f-f3530d1b1ba8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host: Fusion

[cuID:1znfwf0]

**Comment by iLLiCiTiT** [comment]
For this specific exception it should help to raise `ApplicationLaunchFailed` instead of `AssertionError` but it is true that for other crashed actions it would be nice to have this kind of message.

**Comment by BigRoy** [comment]
Fixed with #2505
