### ISSUE TITLE
Validate and sanify openpype settings values when using them

### ISSUE THREAD

**Issue by BenoitConnan** [pypeclub/OpenPype#2502]
**Is your feature request related to a problem? Please describe.**
Hello, i've just encountered a problem while using workfile builder on photoshop and Openpype did not find the file. The cause was a space character before my path in openpype settings.

My fault, yet ... I can't help but feel that a system should exist to sanify
settings assuring no bad entry exists. Actually openpype settings is a simple dict, OpenPype settings should be
a special dict incorparating with custom behaviour to check inputs.

**Describe the solution you'd like**
A class acting as a dict (implementing __getitem__ method or inhereting dict class) returning sanified values (trimed, clamped, defaulted and formated) from settings to users (devs)
Information on each setting sanification could be in current openpype setting's json objects

**Describe alternatives you've considered**
Sanifying inputs on save for openpype settings ? More static, less usefull for formating case.
Sanifying inputs on json load ? Same problem than sanify on save, maybe easyer to debug, yet not as easy than a clearly defined class with __getitem__()
Doing my job and double checking when i change a setting ? Valid point, but a smart setting system could be nifty and open possibilities to other many systems and operations on settings (specificaly path formating)

[cuID:OP-2346]

**Comment by iLLiCiTiT** [comment]
> Actually openpype settings is a simple dict

Well on load it is just dict but there are settings entities used for saving, validation, handling overrides, etc. . We have in plan to validate values more but we have somehow define their validations per entity type which is not as easy considering they should somehow work in Setting UI too.

Your issue can be actually solved right now as path input entity can strip value on save but that's actually all that can do.

**Comment by BenoitConnan** [comment]
As in ... Path input entity trim by default the value or should i add somewhere in the entity an key to true to ask for a trim ?
Because for now, Workfile Builder settings is using path entities and yet I encountered the above issue.

**Comment by iLLiCiTiT** [comment]
Created PR https://github.com/pypeclub/OpenPype/pull/2550
