### ISSUE TITLE
Collect Input Links specifically for each published subsets

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#2509]
**Is your feature request related to a problem? Please describe.**

We want to know exactly which loaded versions were used in the generation of a specific published version of a subset.

OpenPype currently does have some basic logic that [stores all loaded container versions] but [it only so when integrating a workfile](https://github.com/pypeclub/OpenPype/blob/f03472c017bed16d660a5f0f273533a35c94a9e8/openpype/plugins/publish/integrate_inputlinks.py). In a way that makes sense since it collects everything that was loaded in the scene, and not anything that was likely used in the generation of the specific subset. And that's exactly what we'd like to know instead.

We want to know which characters are in renderlayer 'Character' and which backgrounds are in renderlayer 'Environment' and exclude any content that isn't actually in that particular renderlayer even thought they might have been loaded into the work file (for being in the other renderlayer). 

**Describe the solution you'd like**

In colorbleed-config we previously had it implemented like this:

For example like this:
- https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/maya/publish/collect_inputs.py
- https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/houdini/publish/collect_inputs.py
- https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/fusion/publish/collect_inputs.py
And upon integrating:
- https://github.com/Colorbleed/colorbleed-config/blob/76f537eea041f8fed135f2b3334d70e1cf22b528/colorbleed/lib.py#L853-L864

We had tools in place to debug input dependencies and have used small scripts to sync up loaded versions of different geo based on used versions in their input history. Often used for FX or Comp to sync specific layers / assets.

One of the tools was in the repo - but I'm not sure that's currently the latest state but the code shows the overall idea. This tool allows to [show inputs/outputs of a subset](https://github.com/Colorbleed/colorbleed-config/blob/76f537eea041f8fed135f2b3334d70e1cf22b528/colorbleed/plugins/global/load/show_representation_inputs.py) using the [Representation Input/Output tool.](https://github.com/BigRoy/core/blob/acre/avalon/tools/representationinput.py)

Our implementation was functional for Maya, Houdini and Fusion.

**Additional context**

Related to:
- https://github.com/pypeclub/OpenPype/issues/2092 Issue
- https://github.com/pypeclub/OpenPype/pull/2192 PR

It's related to [this Avalon Core issue regarding Inputs/Outputs tracking](https://github.com/getavalon/core/issues/395) where more of our idea/approach is discussed. 
I also mentioned this in OpenPype discord, [here's a trace to that.](https://discord.com/channels/517362899170230292/563751989075378201/930079525604311041)

**Discussion**

I'd love to know if I'm missing existing OpenPype features if this already exists.
Furthermore I'd love to know thoughts from others about how they might like to see this implementation tweaked or used.

**EDIT: _Seeing https://github.com/pypeclub/OpenPype/issues/2092 issue is actually still open this might now just be a duplicate. Sorry. Should we close this in favor of the original? And move any relevant information to there?_

[cuID:OP-2351]

**Comment by mkolar** [comment]
We left the original issue open because it wasn't resolved completely and your info here is totally complementary to that. I agree let's merge them and continue from there, ideally taking what you guys already did, implementing in in OP and we can continue building on top of it. for other families and hosts.
