### ISSUE TITLE
Work Files: Preserve subversion part of filename on incrementing

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#2626]
**Is your feature request related to a problem? Please describe.**

Some Artists are reporting to me that they felt it was off that OpenPype stripped off the 'subversion' suffix part of the filename when incrementing current work file when e.g. submitting the renders to Deadline.

Should the subversion part of the filename persist?

The same happens in the workfiles tool. My current file has a "subversion" part of the string, when clicking "Save" the subversion is empty and if I'd like to preserve the value I need to retype it manually. Should it by default maybe also set the current subverison string in there?

**Describe the solution you'd like**

Preserve as much of the user's file when incrementing workfile as possible.

**Describe alternatives you've considered**

This came up earlier too - where an artist was trying to keep two branches simultaneously. E.g. a special scene with a `_smoke` suffix that is similar to the original lighting scene but optimized and dedicated to rendering only a very small subset with a potentially different renderer too. For that case I've recommened making another `lighting_smoke` task if they want to keep two of those branches simultaneously. Is that what you would recommend too?

[cuID:OP-2560]

**Comment by BigRoy** [comment]
Actually the incrementing of the file for deadline submission doesn't use the same logic as the Work Files tool. Instead that uses [`openpype.lib.path_tools.version_up`](https://github.com/pypeclub/OpenPype/blob/4ce12ffc7c2bf0a406f6cd1bb558e06b27e283f2/openpype/lib/path_tools.py#L22-L74). So we could also only patch that - but somehow I feel both cases are relevant to this issue even though they can be fixed separately.

**Comment by antirotor** [comment]
Connected to this is also request to have dropdown menu in workfile tool with all subversion string so you could select the one that's already there without typing it manually every time you want to save. This is probably more issue for them because it doesn't preserve the subversion.

**Comment by BigRoy** [comment]
> Connected to this is also request to have dropdown menu in workfile tool with all subversion string so you could select the one that's already there without typing it manually every time you want to save. This is probably more issue for them because it doesn't preserve the subversion.

Ah, that would be nice too! :)
