### ISSUE TITLE
Maya: api 'attributes' and 'lib_rendersetup' are two almost identical files

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#2637]
### Issue

It looks like the Maya lib contains basically two almost identical files where
- one has a bugfix but no 'modified for use in OpenPype' message. -> `openpype/hosts/maya/api/lib_renderproducts.py`
- the other doesnt have the bugfix but is 'modified for use in OpenPype' -> `openpype/hosts/maya/api/attributes.py`

I honestly feel `attributes.py` is a more confusing name for a file that solely deals with render setup edits and layers.
Should we remove `attributes.py?` 

I can include the local OpenPype fixes, keep the bugfix that is in lib_renderproducts and refactor the usage to the single file.
Both files are only imported in one other file. 😉

Also, is there a reason `print()` was preferred over `log.debug` (or any type of logging?) That was one of the OP changes made and I don't really see a good reason why that would be better. Especially because the print statement really is debug info and artists wouldn't care.

---

Pinging @antirotor at request of Milan. 🤙 

[cuID:OP-2580]

**Comment by antirotor** [comment]
I agree with everything. This is result of slow refactoring (if we can even call it like that) of Maya code with bits and pieces laying around. Prints should be definitely `log.debug()`. There is a lot of work pending on Maya side in regards to code cleanup - from cleaning whole lib.py file that is so large that it is scary just to look inside, but should be broken to separate files (ideally with unit test? but now I am just dreaming). Also, and that is already mentioned somewhere else - farm specific code should be extracted from maya to deadline (...) module, and so on.

**Comment by BigRoy** [comment]
Thanks. I'll put some effort into some cleanup.
