### ISSUE TITLE
shot/asset description attribute sync ftrack  to db

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#2645]
**Is your feature request related to a problem? Please describe.**
We are not synchronizing Asset or Shot description attribute from ftrack but some productions are asking form distributing those within our toolset

**Describe the solution you'd like**
Enhance SyncToAvalon ftrack action/event to include the Description in synchronization

[cuID:OP-2584]

**Comment by iLLiCiTiT** [comment]
Resolved with https://github.com/pypeclub/OpenPype/pull/2670
