### ISSUE TITLE
Python module `requests` for Py2 and Py3

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#2652]
## Description
We have to have vendorized requests with dependencies for Python 2 hosts as current version is outdated.

[cuID:OP-2589]

**Comment by antirotor** [comment]
With merging of Kitsu integration, this is now priority as currently we have broken build process.

**Comment by mkolar** [comment]
Crap, I didn't notice that when merging.

**Comment by iLLiCiTiT** [comment]
Resolved with https://github.com/pypeclub/OpenPype/pull/3305
