### ISSUE TITLE
Maya integration cleanup

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#2674]
After moving Maya integration to OP it would be nice to clean up the code and unify the behavior of menu functions and give the user more feedback

Reset Resolution is correctly informing the user about performed action in script editor
`# openpype.hosts.maya.api.lib : Setting scene resolution to: 1920 x 1080 # `

but other two (Reset Frame Range and Set Colorspace) are silent and there is no feedback given if operation is successful.

It can help the user to diagnose potential issues in production (wrong shot range entered in Ftrack, etc.)

[cuID:OP-2604]

**Comment by BigRoy** [comment]
This is very loosely related to #1306 - so just dropping this here for future reference.
