### ISSUE TITLE
Project Manager: Disable "scroll" on values like FPS when not selected

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#2677]
**Describe the bug**

When scrolling through the Project Manager (beta) it often happens that the user scrolls and passes an FPS field or Resolution Field. Instead of actually scrolling down in the UI this then means those float values get changed accidentally. And of course this can be very dangerous! :)

Preferably scrolling should not doing anything unless the user is currently editing the value already (and even then, I imagine users would rather be explicit about what value they enter and might not use scrolling).

## Additional context

- https://stackoverflow.com/questions/5821802/qspinbox-inside-a-qscrollarea-how-to-prevent-spin-box-from-stealing-focus-when

From those examples this works well on my end:

```python
from Qt import QtWidgets, QtCore


class SpinBox(QtWidgets.QSpinBox):
    def __init__(self, *args, **kwargs):
        super(SpinBox, self).__init__(*args, **kwargs)
        self.setFocusPolicy(QtCore.Qt.StrongFocus)
    
    def wheelEvent(self, event):
        if not self.hasFocus():
            event.ignore()
        else:
            super(SpinBox, self).wheelEvent(event)

widget = SpinBox()
widget.show()
```

[cuID:OP-2606]

**Comment by BigRoy** [comment]
Reopening this since the issue does actually also exist on non double/float values. In particular on the **Task Type** field.
The Settings UI doesn't suffer from this "scroll changes values" issue. I'm not sure how it's solved there but it might be possible to match settings' behavior?

**Comment by BigRoy** [comment]
> The Settings UI doesn't suffer from this "scroll changes values" issue. I'm not sure how it's solved there but it might be possible to match settings' behavior?

@iLLiCiTiT do you happen to know more about this? :)

**Comment by iLLiCiTiT** [comment]
```
def wheelEvent(self, event):
    if self.hasFocus():
        super(NumberSpinBox, self).wheelEvent(event)
    else:
        event.ignore()
```

**Comment by BigRoy** [comment]
That's what this #2678 did too - are you doing that on the ComboBoxes too?

**Comment by iLLiCiTiT** [comment]
> are you doing that on the ComboBoxes too?

Yes

**Comment by BigRoy** [comment]
I believe this issue is resolved with changing the behavior of edit states in the Project Manager.
