### ISSUE TITLE
Houdini: Increment workfile version on publish

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#2687]
## Request

Houdini is currently missing feature to increment workfile version on publish as for example Maya has.

[cuID:OP-2614]

**Comment by BigRoy** [comment]
Side note: the logic is there - there are two plug-ins already which actually appear to be close to duplicates!

- [`openpype/hosts/houdini/plugins/publish/increment_current_file_deadline.py`](https://github.com/pypeclub/OpenPype/blob/f278b89616c27ecf00d20608bdc11f80678b16ad/openpype/hosts/houdini/plugins/publish/increment_current_file_deadline.py)
- [`openpype/hosts/houdini/plugins/publish/increment_current_file.py`](https://github.com/pypeclub/OpenPype/blob/f278b89616c27ecf00d20608bdc11f80678b16ad/openpype/hosts/houdini/plugins/publish/increment_current_file.py)

But those only trigger for publishes to deadline. So we'd only need to align logic with Maya.
Seems like we can also clean that up along with this! 👍
