### ISSUE TITLE
Settings: Allow searching (ctrl+F) functionality to browse settings

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#2697]
### Feature

I noticed the Settings UI has a Breadcrumbs address bar that autocompletes to valid setting names. Which made me think it shouldn't be impossible to actually implement a 'search' within the settings as well!

I imagine the user clicking `CTRL + F` in the Settings UI or a little search icon next the breadcrumb bar. When doing so a little Search UI shows up where you can e.g. search `Shad` and it lists all entries that are related to "Shader"

```
project_settings/maya/publish/ValidateShaderName
project_settings/maya/publish/ValidateShadingEngine
```

This can be a rudimentary search just based on path, but potentially also on Label and Value. Once the basic functionality for the search is in of course it'll be more trivial to look into improving what you can query on.

I've needed this so many times, just to figure out where something was again. New users could do CTRL + F, type "Tools" and see they are in `Anatomy > Attributes > Tools`. In the little UI they could click on it and it'd set the path in the breadcrumbs address bar, and voila. The user is directly there.

#### Additional notes

Likely a little search UI like this is much more trivial than actually having a real-time search bar that filters the widgets inside the UI since the UI is relatively heavy on the amount of widgets.

I imagine this also reduces the need for #2686 because you'd already be able to identify specific things much faster. User goes CTRL + F, types "Maya" , presses down key to click through the list of search matches and clicks enter. The user is now directly at the right element in settings.

[cuID:25cq45q]

**Comment by BigRoy** [comment]
Here's a functioning prototype. :)


https://user-images.githubusercontent.com/2439881/153628914-eced1388-cb14-4352-8639-5cfc667c8ab9.mp4

**Comment by iLLiCiTiT** [comment]
> Here's a functioning prototype. :)

Where is the PR to merge?
