### ISSUE TITLE
Workfiles: add dropdown to select existing subversion string

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#2719]
## Feature

in **Workfiles**, you can specify subversion string when saving file. This is arbitrary string. It would help to be able to select from existing in dropdown menu then writing every time from the scratch.

![image](https://user-images.githubusercontent.com/33513211/153887810-815b1a0c-32e8-45ef-9cd1-abb9fb28c93e.png)

[cuID:25xn3bh]

**Comment by tokejepsen** [comment]
Or maybe preserve it from previous versions; https://github.com/pypeclub/OpenPype/issues/2626
