### ISSUE TITLE
Loader: multiple asset selection error

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#2728]
**Describe the bug**
When right click on collapsed subset group in multiply selected assets at loader following error is popping up. 

```
Traceback (most recent call last):
  File "/Users/pype.club/code/openpype/openpype/tools/loader/app.py", line 358, in _subsetschanged
    self._versionschanged()
  File "/Users/pype.club/code/openpype/openpype/tools/loader/app.py", line 388, in _versionschanged
    for child in item.children():
AttributeError: 'dict' object has no attribute 'children'
```

**To Reproduce**
1. Open Loader in your DCC
2. Multiply select assets
3. right button click on subset collapsed group

**Expected behavior**
No error but context menu offering

[cuID:25xrr4y]

**Comment by m-u-r-p-h-y** [comment]
was not able to reproduce in Maya

![image](https://user-images.githubusercontent.com/352795/154062757-ded69dad-c91e-41fe-80d2-a2a2480d191b.png)

**Comment by BigRoy** [comment]
Also cannot reproduce this with **multiple assets** selected on the left and right clicking on e.g. a grouping header like `modelMain` or `rigMain`.
Also get no errors when right clicking on a Subset Group (CTRL+G in loader).

_Tested in Maya 2022 however with Py3; this might be a specific Qt version issue?_

**Comment by iLLiCiTiT** [comment]
I can reproduce it. It happens when a group contains color group.

![image](https://user-images.githubusercontent.com/43494761/154066906-e6b15a9e-9598-4385-acb5-c36daba9b1fc.png)

Found out that for proper fix it would need to modify subsets model. Since it is annoying but not crutial bug it is a question if it can't wait for Loader refactor.

**Comment by BigRoy** [comment]
Interesting. I can still right click and it works fine.

I do get this error when LEFT clicking on the top group that has colored groups below it:

```python
# Traceback (most recent call last):
#   File "S:\openpype\OpenPype\openpype\tools\loader\app.py", line 358, in _subsetschanged
#     self._versionschanged()
#   File "S:\openpype\OpenPype\openpype\tools\loader\app.py", line 389, in _versionschanged
#     version_docs.append(child["version_document"])
# KeyError: 'version_document'
```

**Comment by jakubjezek001** [comment]
> _Tested in Maya 2022 however with Py3; this might be a specific Qt version issue?_

thanks for the testing, yeah it seems to be related to different Qt. It is happening in Flame 2021.1 which is P2 and Flame is using its own PySide2.

**Comment by jakubjezek001** [comment]
this is how it looks in Flame 
![image](https://user-images.githubusercontent.com/40640033/154136818-9a7a55bb-886b-4e77-87b8-cac3c9f5bdb2.png)
