### ISSUE TITLE
Houdini: Reset frame range and resolution

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#2740]
## Feature

Implement reset framerange and resolution the same way as it is in Maya,

[cuID:263dfgu]

**Comment by BigRoy** [comment]
> **Reset resolution**

As far as I know Houdini doesn't have a 'current resolution' except for a resolution _per camera_. There is no default camera, and I'm a bit wary about just changing resolutions on ALL cameras in the file. Thoughts?

> **Reset framerange**

Implemented with #2770

**Comment by antirotor** [comment]
Agree, changing resolution here seems to be out of the scope for Houdini.

**Comment by BigRoy** [comment]
> Agree, changing resolution here seems to be out of the scope for Houdini.

Thanks - because of that I've linked #2770 directly to this issue.
