### ISSUE TITLE
extract review data

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#2763]
we are looking for sequences by listing the file system instead of collecting data for extract review during publish and providing exact information about file names, frame ranges, etc.

it is causing a lot of issues and fails caused by other files existing in the same folder like failed temp files of nuke etc.

![image](https://user-images.githubusercontent.com/352795/154686684-33f92900-02a0-4e85-b2d9-7381c54078bf.png)

[cuID:2696j64]

**Comment by jakubjezek001** [comment]
was implemented in https://github.com/pypeclub/OpenPype/pull/3407
