### ISSUE TITLE
unset audio file will cause crash during render publishing

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#282]
## Bug

if `audioFile` is not set in context (should such thing be in context?) test for its existence will fail as `os.path.isfile()` is expecting `str` and will get `NoneType`.

https://github.com/pypeclub/pype/blob/e75167445f3b1dff439bec3bba40e228d6c301d8/pype/plugins/global/publish/submit_publish_job.py#L842-L843

[cuID:PYPE-1124]

**Comment by BigRoy** [comment]
Is this fixed with #284 ?

Or do we still feel this should move to `instance.data["audioFile"]` so that separate instances actually can have its own audio files?

**Comment by antirotor** [comment]
This was fixed with the check for None but audio file is still in the context. I am closing it as it is no longer valid. But the question of audioFile in context vs instance is still present.
