### ISSUE TITLE
Maya: NewScene should reset the context

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#2835]
**Describe the bug**
After publishing (or just saving a workfile) context of a Maya session is set. When artist is done and moving to another task context of the session is kept even after pressing CTRL+N for a NewScene and all data generated by OP are sort of spoiled by wrong data

**To Reproduce**
- set the context of the current Maya session by saving a workfile or publish
- press CTRL +N

see that context of previous operation is kept
![image](https://user-images.githubusercontent.com/352795/156545321-d624c467-8099-468c-905e-386011b4d267.png)

**Expected behavior**
New scene should reset the context

[cuID:OP-2830]

**Comment by BigRoy** [comment]
> New scene should reset the context

Should reset the context to where? :)

For me it works as expected.

1. Launch into Hero
2. Context is Hero
3. Work Files save into Villain
4. Context is Villain
5. New File context remains Villain

To me this is expected behavior?

**Comment by BigRoy** [comment]
> with New Scene I expect to have a clean scene. 

What is that clean scene? What context would that be?

> When modelling in Maya for example I publish a model **and move to another one.**

How are you moving to another one?

> While modelling and creating new Model instance it will get attributes from previous context.

This is not the case, right? Unless you kept open the Creator UI (and thus the `asset` field never got updated?) or you created the model before saving into the new context and thus you had never switched the context to the new asset in the first place?

**Comment by BigRoy** [comment]
> as new Publisher is actually addressing this perfectly.

Could you briefly explain how the new Publisher is solving this issue?
