### ISSUE TITLE
Serialization of ObjectId

### ISSUE THREAD

**Issue by zhoub** [pypeclub/OpenPype#2849]
**Describe the bug**
From the method load of loader plugin, just add a debug line

**To Reproduce**
Just add a line of load plugin
```python
def load(self, context, name=None, namespace=None, options=None):
    import json
    print(json.dumps(context))
```

It prints ObjectId isn't serializable, which is just a string.

**Expected behavior**
The context should be able to be serialized into JSON string.

**Desktop (please complete the following information):**
Install 3.8.2
 - OS: Windows
 - Host: Maya

[cuID:22yjqzc]

**Comment by antirotor** [comment]
ObjectId is not directly serializable to JSON, context in this case is Python dictionary and I am not sure we cast it to JSON anywhere. If you access it with python, you'll get the id as a `str`

**Comment by BigRoy** [comment]
> The context should be able to be serialized into JSON string.

Could you explain your use case as to why you'd expect this and why you would potentially need that?

**Comment by zhoub** [comment]
Just for debug purpose, if this ObjectId is simple enough as UUID, it should be able to be serialized.

**Comment by antirotor** [comment]
ObjectId is mongodb object and is missing `.toJSON()` method to allow easy serialization from python dict to json and that is why it is failing. You can convert it when data are retrieved from database, but I see no reason to do it - you can debug it as easy with python dicts (just with plain old `pprint` module for example) and if you need json from it, you can provide your own serialization methods for it. Be aware that context can contain other objects as well, not all could be easily serializable to any form.

**Comment by zhoub** [comment]
Ok
