### ISSUE TITLE
Removed/renamed/changed document in MongoDB may crash gui

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#287]
Issue:
Edge case situation, happened to me only during developing, but if `asset` was removed or changed to `archived_asset` then GUI showing the project will crash:
```
Traceback (most recent call last):
  File "C:\Users\jakub.trllo\Desktop\pype\pype-setup\repos\pype\pype\modules\standalonepublish\app.py", line 135, in on_asset_changed
    self.widget_family.change_asset(asset['name'])
TypeError: 'NoneType' object is not subscriptable
```

[cuID:PYPE-1116]

**Comment by mkolar** [comment]
We haven't encountered this since it was reporting and v4 is moving to postgres with REST and graphQl access, so I'm closing this as obsolete
