### ISSUE TITLE
Blender: 3.1.0 Support

### ISSUE THREAD

**Issue by zhoub** [pypeclub/OpenPype#2890]
**Is your feature request related to a problem? Please describe.**
Launch blender 3.1.0 from Launcher, the menu OpenPype was not created after blender started.

**Describe the solution you'd like**
It should be the same as 2.9.x

**Describe alternatives you've considered**

**Additional info**
<img width="605" alt="image" src="https://user-images.githubusercontent.com/1798206/158309150-eda761ac-641e-49b1-86e8-780a2d25b3cf.png">

**Comment by m-u-r-p-h-y** [comment]
this is actually not an issue. closing

**Comment by m-u-r-p-h-y** [comment]
blender 3.1.0 is working perfectly fine

not sure why it did not work for @zhoub at that time, but it is quite a long time back and there is no point to have the issue opened as there is no relevant info about the error, and it is impossible to replicate.

no problem to reopen it, if more information is provided . . .

thx

![image](https://user-images.githubusercontent.com/352795/188817290-2b59fb08-c5f1-4f71-a501-2f44c283c0bc.png)
