### ISSUE TITLE
Natron: Support as Nuke

### ISSUE THREAD

**Issue by zhoub** [pypeclub/OpenPype#2910]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support Natron as Nuke

**Describe alternatives you've considered**
No alternative

**Additional context**
https://github.com/NatronGitHub/Natron

**Comment by tokejepsen** [comment]
I thought Natron had died/stagnated due to the main developer leaving the project?

**Comment by ClementHector** [comment]
Yes, he left to develop another compositing software.

**Comment by zhoub** [comment]
Sorry, which is that alternative compositing software ?

**Comment by antirotor** [comment]
I'll close this now until (if) proper push for Natron support comes.
