### ISSUE TITLE
Nuke: Render Creator doesn't handle Integer and Boolean knobs

### ISSUE THREAD

**Issue by jrsndl** [pypeclub/OpenPype#3013]
**Describe the bug**
Using integer knob in project_anatomy/imageio/nuke/nodes/requiredNodes/0/knobs breaks creating render node

**To Reproduce**
1. Go to Settings, project_anatomy/imageio/nuke/nodes/requiredNodes/0/knobs
2. Set file_type:exr, compression:DWAB, dw_compression_level:60
3. Launch Nuke, create render node
4. See error:
```
Traceback (most recent call last):
  File "C:\Users\robur\OpenPype\openpype\tools\creator\window.py", line 435, in _on_create
    data={"variant": variant}
  File "C:\Users\robur\OpenPype\openpype\pipeline\create\legacy_create.py", line 152, in legacy_create
    instance = plugin.process()
  File "<string>", line 127, in process
  File "C:\Users\robur\OpenPype\openpype\hosts\nuke\api\lib.py", line 931, in create_write_node
    **_data
  File "C:\Users\robur\OpenPype\openpype\hosts\nuke\api\lib.py", line 389, in add_write_node
    w[k].setValue(v)
ValueError: expecting a sequence of 1 floats, 2 found
```

**Expected behavior**
Settings should allow Nuke Integer knobs

**Desktop (please complete the following information):**
Windows 10, Nuke 12.2 (Python 2)

**Additional context**
Possibly conversion issue?
https://github.com/pypeclub/OpenPype/blob/143f7b8ac4eb9f8dcc00e9f27373d820a87132d5/openpype/hosts/nuke/api/lib.py#L355

[cuID:OP-3036]

**Comment by jrsndl** [comment]
It also doesn't set boolean values. It just ignores them in settings and doesn't fail.
IMHO this might happen some time ago when Nuke implementation was moved from Avalon.
Maybe @iLLiCiTiT  might know how to fix it?

**Comment by iLLiCiTiT** [comment]
Is this still an issue? @jakubjezek001 you've looked into the code recently, can you check and validate?
