### ISSUE TITLE
Cannot publish multiple review subsets in Maya

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#3034]
## Bug

When you create mutliple review instances in Maya, only one will be published.

### To replicate

1) Create review instance `main` and put one camera there
2) Create another instance `second` and put another camera there
3) Publish ...
4) Publishing will look fine, but only one instance will be integrated

[cuID:25zv2aa]

**Comment by antirotor** [comment]
> That might have been when I implemented it with Milan suggestion.

> > From 2.13 or 14, we can then switch it OFF by default. and in pype 3 remove it. what do you think?

That is probably important point in conversation ... Question is - this should be probably reworked so it conforms with new subset name templating and it has to include variant so we can fix this issue. How to work with backwards compatibility in that regard. It is little related in this regard with #2695

**Comment by tokejepsen** [comment]
Is it a direction decision that is needed to continue on this?

**Comment by antirotor** [comment]
> Is it a direction decision that is needed to continue on this?

I think we need to agree on how to handle backwards compatibility.

**Comment by kalisp** [comment]
Closed by https://github.com/pypeclub/OpenPype/pull/3269
