### ISSUE TITLE
General: Farm publishing

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#3058]
**Is your feature request related to a problem? Please describe.**

Hosts have renderfarm implementations for rendering (e.g. Maya -> Deadline) but there currently is no simple and consistent way to publish (anything outside of that) on the farm.

Goals:

- From a host it should be trivial to submit for a publish on the farm in a familiar manner to how regular publishes work. 
- I'd like to still perform a "publish" with Pyblish for validation as per usual so that you can catch any validation errors before submitting to the farm. The farm machine then triggers the same validations again to confirm everything is ok.
- Be able to select which instances in the current scene you'd like to submit on the farm (so enabling/disabling an instance would work)
- Preferably it's a feature that is easy to implement for new hosts.
- Allow to submit to farm as a single job for all instances or a publish job per instance
- Have the entry point to run the publish in the host be simple enough to easily implement for different Render managers (e.g. Deadline, Royal Render, Muster, OpenCue, etc.)

**Describe the solution you'd like**

This is how we had implemented it before where it would somewhat universal across all hosts.

Note: Whenever I mention `target=farm` below we originally used `target=deadline`.

1. Have a menu entry somewhere to "Submit publish to the farm"
2. This runs Pyblish with a different `target`, e.g. `target=farm` whereas we had a [default target added `target=local`](https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/__init__.py#L23-L25) otherwise.
    - Extractors+Integrators would only run for `target=local` so would not trigger for submit to farm.
    - Collectors + Validators would run for `target=default` (This was always set no matter the registered target. So validators would always trigger.)
        - We did have some validators that were set to `target=farm`. E.g. a Validator for a Playblast/review family that would always error to disallow submitting reviews to the farm, since playblasting doesn't work in mayabatch without a gui.
3. [Submit to the farm](https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/maya/publish/submit_maya_publish_deadline.py#L61-L69](https://github.com/Colorbleed/colorbleed-config/blob/76f537eea041f8fed135f2b3334d70e1cf22b528/colorbleed/plugins/maya/publish/submit_maya_publish_deadline.py#L32-L142)) would only trigger on [`target=farm`](https://github.com/Colorbleed/colorbleed-config/blob/76f537eea041f8fed135f2b3334d70e1cf22b528/colorbleed/plugins/maya/publish/submit_maya_publish_deadline.py#L48) - _this could have been a generic global plug-in if the Deadline Plug-in was set elsewhere, e.g. this uses `MayaBatch`_
4. Trigger the publish on the Deadline worker. This would [just do `pyblish.util.publish()` in a Deadline Job within the host.](https://github.com/Colorbleed/colorbleed-config/blob/76f537eea041f8fed135f2b3334d70e1cf22b528/colorbleed/lib.py#L478-L480) We did trigger them e.g. through `MayaBatch` or `HoudiniBatch` plugins of Deadline to preserve as much of the "progress" tracking of the host stdout messages of those particular hosts - but technically could also run through a custom plug-in that can trigger a Python script inside a host application.

1. We would pass it [a Python script to run in the host](https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/scripts/publish_instances.py) on the farm - which calls this [`publish_remote()`](https://github.com/Colorbleed/colorbleed-config/blob/76f537eea041f8fed135f2b3334d70e1cf22b528/colorbleed/lib.py#L467-L497)

Here are the original PRs related to this features: [Maya](https://github.com/Colorbleed/colorbleed-config/pull/238) & [Houdini](https://github.com/Colorbleed/colorbleed-config/pull/251) however the implementation was cleaned and simplified over time but might help point you to what areas of the code are related to the remote publishing. 

---

Related to:

- #2722 

[cuID:OP-3097]

**Comment by tokejepsen** [comment]
Another thing related to farm publishing is whether to use the native plugins of the render farm software. For example instead of using Deadlines native `MayaBatch` plugin to render, we would go through the same `OpenPype` plugin. This would negate any work Deadline does to optimize the rendering process, but it would allow for a very generalized plugin approach to farm publishing in general. What you see in Maya is what you get in Deadline.
Personally I've found that Deadline sits on legacy code because they are catering to lots of legacy clients so updating the plugins does not happen very often. Also if you improve on the publishing process locally that could benefit the farm publishing and hence all OpenPype users.

> I'd like to still perform a "publish" with Pyblish for validation as per usual so that you can catch any validation errors before submitting to the farm. The farm machine then triggers the same validations again to confirm everything is ok.

I would argue that the farm should be skipping validations cause we need to catch issues before it gets sent off to the farm. Also running the same validation again might be time consuming.

The whole `OpenPype` plugin to any farm, could be as simple as this; https://github.com/pypeclub/OpenPype/blob/2.x/develop/pype/scripts/export_maya_alembic_job.py

> This runs Pyblish with a different target, e.g. target=farm whereas we had a [default target added target=local](https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/__init__.py#L23-L25) otherwise.

Could you see this implemented as an attribute on the instance instead of a dedicated "different" publish?
Maybe we need to do a breakdown of the two approaches with pros/cons etc.

**Comment by pberto** [comment]
I think doing it **outside** of deadline is a very good idea.

**Comment by BigRoy** [comment]
> I would argue that the farm should be skipping validations cause we need to catch issues before it gets sent off to the farm. Also running the same validation again might be time consuming.

The validators are trigger before TOO - but it's just a security detail to ensure that between the time of submission and the actual deadline worker doing its job that it still passes and also that the worker has access to the same things that it needs to perform the publish, like Plug-ins, additional files outside of Maya itself. This is extra important if you submitted from e.g. a Windows machine and e.g. the Dealdine Worker is on Linux. I'd definitely default to validating on both ends.

> Another thing related to farm publishing is whether to use the native plugins of the render farm software. For example instead of using Deadlines native MayaBatch plugin to render, we would go through the same OpenPype plugin. This would negate any work Deadline does to optimize the rendering process, but it would allow for a very generalized plugin approach to farm publishing in general. What you see in Maya is what you get in Deadline.
Personally I've found that Deadline sits on legacy code because they are catering to lots of legacy clients so updating the plugins does not happen very often. Also if you improve on the publishing process locally that could benefit the farm publishing and hence all OpenPype users.

I'd like to simplify as much as possible. But there were some good reasons to stick to the particular maya plug-ins.

But you might still need to separately track 'progress' from stdout for long running jobs, e.g. a Houdini ROP node might take 20 minutes. With the Houdini plug-in you get progress tracking from the Output. With a custom plug-in you'd need to explicitly capture stdout errors from Houdini processes, from Maya, etc. And also regex match these progress messages in its stdout.

I felt at the time it was better to report issues to Deadline so the software worked better over time for anything in Deadline than leaving the mess in Deadline and working with our own plug-in since it just meant more development maintenance moved to myself at the time instead of relying on the render manager that comes with support.

> Could you see this implemented as an attribute on the instance instead of a dedicated "different" publish?
Maybe we need to do a breakdown of the two approaches with pros/cons etc.

We actually did something like that in Houdini at the time - where a separate node identified whether the scene should submit to Deadline. It wasn't more intuitive really - but I guess nothing is holding us back to force a particular instance to always submit to the farm. However, if only for a particular Instance instead of the full publish context then Pyblish targets can't be used.

A pro would be that a scene would always default to submitting to the farm instead of depending on the menu entry you clicked. And it allowed options like what particular pool you'd want to submit that publish job into.

A con was that it worked differently from regular publishing.

> I think doing it **outside** of deadline is a very good idea.

Totally agree. 

The core entry point of the described feature is to [run a python script in the host](https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/scripts/publish_instances.py) with some predefined [environment variables](https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/maya/publish/submit_maya_publish_deadline.py#L124-L126). As long as you're able to do that with your render manager of choice then you're good.

**Comment by tokejepsen** [comment]
> I felt at the time it was better to report issues to Deadline so the software worked better over time for anything in Deadline than leaving the mess in Deadline and working with our own plug-in since it just meant more development maintenance moved to myself at the time instead of relying on the render manager that comes with support.

Yeah, I would agree that as a solo developer, you need to utilize the support of the software you are paying for. BUT now that OpenPype is going beyond a single render farm manager and solo development, having a unified entry point for rendering on the farm/locally might be the better option.

> We actually did something like that in Houdini at the time - where a separate node identified whether the scene should submit to Deadline. It wasn't more intuitive really - but I guess nothing is holding us back to force a particular instance to always submit to the farm. However, if only for a particular Instance instead of the full publish context then Pyblish targets can't be used.

So with alembic publishing on the farm we have an attribute on the pointcache objectset in Maya `Farm` which you just toggle depending whether you want it local or remote published.
Having it on individual instances would allow for "one" publish. For example we might have local pointcache extracting first before it gets published on a farm, but the local pointcache extraction and a potential farm Maya render would the "same" publish for the user. Having two publishing entry points would mean that the user has to submit twice. Hope that make sense?
Having it on individual instances would allow for more flexible development. For example we might have implemented farm extraction on pointcaches but not bifrost caches. Pointcaches can continue to be processed on the farm while we figure out or find time to extract bifrost on the farm. Users can still publish the bifrost caches locally though.

**Comment by BigRoy** [comment]
@iLLiCiTiT @kalisp I feel like this issue was never _actually_ completed by anything? I can't find the reason why this got closed. Any idea?
