### ISSUE TITLE
Shotgrid Integration

### ISSUE THREAD

**Issue by zhoub** [pypeclub/OpenPype#3211]
**Is your feature request related to a problem? Please describe.**
Merge the contribution from [Add Shotgrid module PR](https://github.com/pypeclub/OpenPype/pull/2921) into OP.

**Describe the solution you'd like**
Let OP support SG.

**Describe alternatives you've considered**
None.

**Additional context**
None.

[cuID:OP-3272]

**Comment by BigRoy** [comment]
Thanks @zhoub - I believe the major point currently is testing the feature set before merging.

I believe @pberto was still [looking into testing it as was commented on the open PR](https://github.com/pypeclub/OpenPype/pull/2921#issuecomment-1102319332).

**Comment by zhoub** [comment]
We will start to test and work on this soon.

**Comment by mkolar** [comment]
considering this already has a PR, that is being reviewed and is waiting for some final merges on the source side, I'm closing this.
