### ISSUE TITLE
Sync server: Load settings for single project

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#3231]
## Description
Sync server does not have ability to retrieve settings for only one project but always cache all available projects. This is ok when sync server is running in tray but it is a big issue and slowdown when it's used in host e.g. in loader tool.

### Addicitonal info
There should be also some kind of cache invalidation after some timeout to be able refresh settings after some time.

[cuID:]

**Comment by kalisp** [comment]
Fix in https://github.com/pypeclub/OpenPype/pull/3280
