### ISSUE TITLE
OpenImageIO tool detection not working as expected

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#3276]
## Problem

We have mechanism to detect `oiiotool` from OpenImageIO that is included in OpenPype build at `/vendor/bin/oiio`. Problem with the detection is that it doesn't take into consideration different structure of OpenImageIO on different platforms. It basically expects `oiiotool` to be present at `/vendor/bin/oiio/linux/oiiotool` but under linux (and macos) it is `/vendor/bin/oiio/linux/bin/oiiotool` - notice that additional `bin` there. This is pretty standard layout in unix world where you bundle executable in different directory than libraries.

This must be addressed:

- Unify layout across the platforms to have that `bin` folder
- or add one level up script file or symlink 
- or have logic in the code adding `bin` as necessary

I  vote for the first option.

[cuID:2eqzt7p]

**Comment by iLLiCiTiT** [comment]
I vote for option 3. We already use that validation here https://github.com/pypeclub/OpenPype/blob/develop/start.py#L445 and here https://github.com/pypeclub/OpenPype/blob/develop/setup.py#L38 .

**Comment by iLLiCiTiT** [comment]
Resolved with https://github.com/pypeclub/OpenPype/pull/3278
