### ISSUE TITLE
Maya: Camera settings overrides are not working

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3573]
**Describe the bug**

Project camera settings overrides for extract playblast in Maya are not working

**To Reproduce**
set the camera overrides in settings and publish review

**Screenshots**
![image](https://user-images.githubusercontent.com/352795/181025747-a366651d-f7ae-4cf3-8463-be662c4dca42.png)

**Desktop :**
 - OS: Windows
 - Host: Maya 2022.4
 - latest develop

[cuID:OP-3648]

**Comment by Allan-I** [comment]
Thank you Murphy, I'll fix this as I worked on this code earlier and it shouldn't take long.
