### ISSUE TITLE
Environment variables config bug on Windows

### ISSUE THREAD

**Issue by friquette** [pypeclub/OpenPype#3585]
**Describe the bug**
On Windows, you can't put an environment variable in the PYTHONPATH set in OpenPype settings, unlike on Linux.

**To Reproduce**
OpenPype crashes at the start if you have something like this in the settings:
```
{
    "STUDIO_SOFTWARE": "/prod/softprod/apps",
    "PYTHONPATH": [
        "{PYTHONPATH}",
        "{STUDIO_SOFTWARE}"
    ]
}
```
You need to have something like that in order to work on Windows:
```
{
    "STUDIO_SOFTWARE": "/prod/softprod/apps",
    "PYTHONPATH": [
        "{PYTHONPATH}",
        "/prod/softprod/apps"
    ]
}
```

**Screenshots**
This is the error we got:
![image](https://user-images.githubusercontent.com/51854004/181281160-8af14594-8a51-49e3-8ab5-f755edaa8734.png)

**Expected behavior**
The first pattern should work on Windows as it works on Linux.

**Desktop (please complete the following information):**
 - OS: Windows

[cuID:2nbq137]

**Comment by antirotor** [comment]
Resolved by #3587
