### ISSUE TITLE
New integrator force to have dot before frame in filename

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#3608]
## Description
New integrator won't resolve sequences in files unless the frame starts with dot. This filenames `["frame_0001.png", "frame_0002.png"]` won't be resolved as sequence.

## Suggested solution
At this moment we just expect that list of files on representation is a sequence at multiple places. All we need to do is to replace custom function `assemble` with `clique.assemble` without any additional arguments.

[cuID:2nx4qtv]

**Comment by BigRoy** [comment]
> At this moment we just expect that list of files on representation is a sequence at multiple places. All we need to do is to replace custom function assemble with clique.assemble without any additional arguments.

I believe this will break detecting single files named `hello_00.00.exr` as far as I'm aware. It'll correctly detect sequences because it knows which is the frame counter from the collection, but it won't work with assembling from a single frame.

**Comment by iLLiCiTiT** [comment]
It never did work for assembly of single frame. We always expect that the list in files is a sequence at multiple places (not just in integrator) so if there is single file or invalid sequence it would crash much earlier.

**Comment by BigRoy** [comment]
> It never did work for assembly of single frame. We always expect that the list in files is a sequence at multiple places (not just in integrator) so if there is single file or invalid sequence it would crash much earlier. Also you can't have underscore before frames (or udims) or you can't have filenames just containing the frame.

I believe it actually DID work with this integrator before this PR for e.g. a single frame maya submission to deadline and publish. Can you confirm a single frame (start frame 1001, end frame 1001) still publishes correctly after this fix?

**Comment by iLLiCiTiT** [comment]
> I believe it actually did work with this integrator before this PR

I think it would crash in extract review or other plugins working with representation files before it would get to integration.

> Can you confirm a single frame (start frame 1001, end frame 1001) still publishes correctly after this fix?

I don't know. I think it will be published as single file without frame in filename, we can check it out. I understand that issue, but at the same time this is not way how it should be fixed. Forcing the dot broke almost all hosts and in some cases we don't have a way how to make sure there is a dot before frame (e.g. standalone publisher).

**Comment by BigRoy** [comment]
> Forcing the dot broke almost all hosts and in some cases we don't have a way how to make sure there is a dot before frame (e.g. standalone publisher).

I understand. However - I recall mentioning/discussing it explicitly. And preferably we'd "assemble" it the same everywhere so that at least the output was consistent. Previously the expected output from just `clique.assemble` wasn't consistent enough to be solid for production, because e.g. `hero01.1001.exr` went crazy when rendering a single frame. Etc.

Anyway, let's continue to solve for all cases and just make sure we test the different cases.

1 frame, multiple frames, different naming conventions. If those work and use the same logic across the different plug-ins then 🚀 🥇 !
