### ISSUE TITLE
Audio on Compositing Reviews

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/OpenPype#368]
**Goal**

When publishing from Nuke, similar to Maya, we want audio on the reviews.

**Implementation**

Nuke does not have any audio node to reference, so the best place to grab the audio from would be by looking in a specific place in the database. Something like shot > audio.

[cuID:PYPE-1356]

**Comment by tokejepsen** [comment]
Only `audioMain` subset is currently supported. Further development is needed to support configurable subsets.

**Comment by mkolar** [comment]
Once we port nuke to 3.0 this will be possible to do in settings

**Comment by tokejepsen** [comment]
With this PR the subset name can be configured; https://github.com/pypeclub/pype/pull/1073
