### ISSUE TITLE
Modules crash in Python 2 hosts

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#3696]
## Bug

When running Python 2 based host I get this error during the startup:

```
Traceback (most recent call last):
  File "C:\Users\annat\Documents\pype\3.0\openpype\modules\base.py", line 366, in _load_modules
    import_str, fromlist=("", )
  File "C:\Users\annat\Documents\pype\3.0\openpype\hosts\unreal\__init__.py", line 6
    def add_implementation_envs(env: dict, _app: Application) -> None:
                                   ^
SyntaxError: invalid syntax
```

This is not that critical as it seems it doesn't break anything, but in case of Houdini this error is presented to user in scary way 😱 

[cuID:]

**Comment by BigRoy** [comment]
> but in case of Houdini this error is presented to user in scary way

That code error seems to happen with the `unreal` host - how come Houdini is loading that?
Those Py3 type hints are only added in the unreal host implementation.

**Comment by antirotor** [comment]
I think this is because all modules are touched during init so if some code in them is using py3 syntax, this will happen. It is happening even in Maya 2020 so it is not Houdini specific and problably not even Unreal related. Unreal is just victim of being currently the only one containing py3 code there.

**Comment by iLLiCiTiT** [comment]
> However, I feel like Host modules shouldn't get loaded unless when running the host. No?

Hosts are becoming modules, thus they should follow same rule: public code should not use any vendor specific imports and must be Py2 and Py3 compatible. Right now only maya is defined as module, but all hosts will be defined as modules too. Side effect is that all folders in hosts folder are imported too. We probably didn't notice during testing of https://github.com/pypeclub/OpenPype/pull/3647 that unreal has this issue.
