### ISSUE TITLE
Kitsu module: Drop entities root settings

### ISSUE THREAD

**Issue by Tilix4** [pypeclub/OpenPype#3738]
### Discussed in https://github.com/pypeclub/OpenPype/discussions/3545

<div type='discussions-op-text'>

<sup>Originally posted by **Tilix4** July 20, 2022</sup>
In settings, you can customize the entities root folders for `assets` and `shots`:
![image](https://user-images.githubusercontent.com/22875539/180030789-e2dd0efb-5a45-46a9-b31f-ede7a4836482.png)

This allows you to create a tree of folders where all assets or shots will be put under. The issue is, I don't see any use case where we will need more than `Assets/` or `Shots/` to put all the related entities.
Moreover, that's how things are classified in Kitsu: 
![image](https://user-images.githubusercontent.com/22875539/180031209-ba042edb-4c5a-4d2c-90f2-a3edfc31ead6.png)

Therefore, I propose to drop this settings feature to keep a simple `Assets` and `Shots`, not customizable.
![image](https://user-images.githubusercontent.com/22875539/180031477-e76fa7b1-a47f-40a4-8151-1144a99c6832.png)
</div>

[cuID:OP-3831]

**Comment by BigRoy** [comment]
Actually what if the studio is keen on enforcing it's lowercase within OpenPype? Without this they couldn't do so?

**Comment by Tilix4** [comment]
You're right, this topic hasn't been discussed. The current system is to strictly match Kitsu's hierarchy. If this is really an issue, I can add a setting to configure it with `lower`, `upper` or `capitalize`.

**Comment by BigRoy** [comment]
> If this is really an issue, I can add a setting to configure it with lower, upper or capitalize.

Somehow I feel that _if_ there's any reason to allow customization to e.g. change `Assets` to `assets` I don't see why we couldn't keep it as we have it now. Kind of feels like that logic would at least be similar in code complexity and the current implementation allows more customization for any studio to do as they please? Plus the customization that it allows doesn't seem like anything that would really break the pipeline if you customize it. (Unless someone would maybe type `*s;.s><  _19!` or odd characters in that settings field)
