### ISSUE TITLE
Poetry build fails with PEP 440 version error

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#3767]
## Problem

Poetry from some version is forcing PEP-440[^1] as version specification format. We are using semver 2.0[^2] and that is not compatible. If OpenPype version is specified in `pyproject.toml` like `version = "3.14.1"` then all is good, but with `version = "3.14.1-nightly.1"` build fails with PEP-440 error.

## Solution

We can normalize[^3] semver format to PEP-440. So `3.14.1-nightly.2` will become `3.14.1nightly.2`.

[^1]: https://peps.python.org/pep-0440/
[^2]: https://semver.org/
[^3]: https://peps.python.org/pep-0440/#normalization

[cuID:OP-3869]

**Comment by iLLiCiTiT** [comment]
Eh, the regex is `[N!]N(.N)*[{a|b|rc}N][.postN][.devN]` so the `nightly` part won't match it.

**Comment by antirotor** [comment]
So it seems that to transform our nightly builds to PEP-440 compatible string we should do this:

`X.Y.postN.devM   # Developmental release of a post-release`

so `3.14.1-nightly.1` should be `3.14.post1.dev1`

**Comment by kalisp** [comment]
Fixed by https://github.com/pypeclub/OpenPype/pull/3777
