### ISSUE TITLE
General: Integrate Hero Version is not working

### ISSUE THREAD

**Issue by LiborBatek** [pypeclub/OpenPype#3805]
Maya 2022 host:

When publishing asset look with "Integrate Hero Version" turned ON (defaults) publishing fails... 

Hero publish version folder contains already some data in previous hero folder but obviously not all of them because of some previous publish fail...
![image](https://user-images.githubusercontent.com/112623825/188905935-692c5d89-a61e-4fc5-a343-aa63d65327b6.png)

missing files in previous published folder example here:
![image](https://user-images.githubusercontent.com/112623825/188906236-02ea26f9-d08c-4885-8575-0d2326a5e09d.png)

It misses maya files and JSON file...

[cuID:OP-3923]

**Comment by m-u-r-p-h-y** [comment]
can we see the full traceback of the error pls.

**Comment by LiborBatek** [comment]
here it is, btw this particular asset have previous hero version with all components ok (no missing published data) and still failed to integrate hero version...
```
Instance: 
modelMain
Message: 
[WinError 1] Incorrect function: 'P:\\PROJECTS\\OP01_CG_demo\\assets\\props\\airConditionerB\\publish\\model\\modelMain\\v001\\cg_airConditionerB_modelMain_v001.ma' -> 'P:\\PROJECTS/OP01_CG_demo/assets/props/airConditionerB/publish/model/modelMain/hero/cg_airConditionerB_modelMain_hero.ma'
Line: 
52
Traceback: 
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\plugins\publish\integrate_hero_version.py", line 95, in process
  File "D:\REPO\OpenPype\openpype\plugins\publish\integrate_hero_version.py", line 421, in integrate_instance
  File "D:\REPO\OpenPype\openpype\plugins\publish\integrate_hero_version.py", line 582, in copy_file
  File "D:\REPO\OpenPype\openpype\lib\path_tools.py", line 52, in create_hard_link
    os.link(src_path, dst_path)
OSError: [WinError 1] Incorrect function: 'P:\\PROJECTS\\OP01_CG_demo\\assets\\props\\airConditionerB\\publish\\model\\modelMain\\v001\\cg_airConditionerB_modelMain_v001.ma' -> 'P:\\PROJECTS/OP01_CG_demo/assets/props/airConditionerB/publish/model/modelMain/hero/cg_airConditionerB_modelMain_hero.ma'

```

**Comment by BigRoy** [comment]
It's failing to produce a hardlink with `os.link`. 
Note that `os.link` should error if the destination path already exists. As such, that's likely your case?

If that's the case:
We might want to do `force_link` it, for example like this: https://stackoverflow.com/a/58957613
Here's a similar topic regarding symlinks instead: https://stackoverflow.com/a/55742015

Which makes me wonder - why hasn't this come up earlier? I feel like this should have probably even happened for ALL non-first hero publishes? However, the logic above should actually backup the existing hero folder first, like done [here](https://github.com/pypeclub/OpenPype/blob/develop/openpype/plugins/publish/integrate_hero_version.py#L246-L292). Maybe that's failing for these look publishes? But your traceback shows it for a model publish. So it's not just looks?

Interesting!

**Comment by iLLiCiTiT** [comment]
We found out that Hero publishing does not work at all because of some differences in new and legacy integrator. We'll discuss priority of this bug today.

**Comment by LiborBatek** [comment]
Accidentally forgot turning off "Integrate Hero Version" during publish of mayaScene family and this error msg popped out...
fi not useful for you guys just nevermind...

```
Instance: 
mayaSceneMain
Message: 
[WinError 1] Incorrect function: 'P:\\PROJECTS\\OP01_CG_demo\\assets\\setups\\lookDev\\publish\\mayaScene\\mayaSceneMain\\v001\\cg_lookDev_mayaSceneMain_v001.ma' -> 'P:\\PROJECTS/OP01_CG_demo/assets/setups/lookDev/publish/mayaScene/mayaSceneMain/hero/cg_lookDev_mayaSceneMain_hero.ma'
Line: 
91
Traceback: 
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\plugins\publish\integrate_hero_version.py", line 94, in process
  File "D:\REPO\OpenPype\openpype\plugins\publish\integrate_hero_version.py", line 420, in integrate_instance
  File "D:\REPO\OpenPype\openpype\plugins\publish\integrate_hero_version.py", line 575, in copy_file
  File "D:\REPO\OpenPype\openpype\lib\path_tools.py", line 91, in create_hard_link
    os.link(src_path, dst_path)
OSError: [WinError 1] Incorrect function: 'P:\\PROJECTS\\OP01_CG_demo\\assets\\setups\\lookDev\\publish\\mayaScene\\mayaSceneMain\\v001\\cg_lookDev_mayaSceneMain_v001.ma' -> 'P:\\PROJECTS/OP01_CG_demo/assets/setups/lookDev/publish/mayaScene/mayaSceneMain/hero/cg_lookDev_mayaSceneMain_hero.ma'

```

**Comment by LiborBatek** [comment]
Sorry guys, shouldnt close this pull request too soon. I wont do it in the future tho.
Thx
L.

**Comment by m-u-r-p-h-y** [comment]
> Sorry guys, shouldnt close this issue too soon. I wont do it in the future tho. Thx L.

if it is a valid issue, there is no problem re-opening it . . .
