### ISSUE TITLE
Loader: mutliselection loading not working on matching representation

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#3863]
**Describe the bug**
Multiselection of assets and RMB click on either group or multiselected subsets is not offering loading for representation in common. 

**To Reproduce**
1. Open loader in any host and context
2. Multiselect assets where you are sure you have subsets with representations in common.
3. RMB click on group or inside on multiple subsets 
4. Notice there are missing some representations which are in common.

**Expected behavior**
It should behave the same way as if single asset / subset was selected

**Screenshots**
Multiselection RMB click on group
![image](https://user-images.githubusercontent.com/40640033/190404900-5b8a9d7b-5f55-4149-a241-e40ca02dae66.png)

Multiselection RMB click on multiple selected subsets:
![image](https://user-images.githubusercontent.com/40640033/190405051-e92d34ae-4720-4bb8-8bbe-4b9be6a7d6c3.png)

Single asset / subset selected:
![image](https://user-images.githubusercontent.com/40640033/190405198-5c44b906-3622-42d5-b5cb-e90e0e3225f3.png)

**Additional context**
Those missing representations are custom named and perhpas it is happending because representations are having slightly different data? Just suggestion..

[cuID:OP-4054]

**Comment by BigRoy** [comment]
> Those missing representations are custom named and perhpas it is happending because representations are having slightly different data?

This would happen if the representations have different names. Is that the case? Do ALL have the exact `pWrACEScg` representation?

**Comment by jakubjezek001** [comment]
> This would happen if the representations have different names. Is that the case? Do ALL have the exact `pWrACEScg` representation? If so, then it would list it.

Yes, it is not happening even it is having `pWrACEScg` in common.

**Comment by iLLiCiTiT** [comment]
Resolved by https://github.com/pypeclub/OpenPype/pull/4053
