### ISSUE TITLE
Davinci QT binding not found

### ISSUE THREAD

**Issue by aramadan0096** [pypeclub/OpenPype#3911]
**Running version**
3.14.1

**Describe the bug**
OpenPype menu not working.

**To Reproduce**
1. Go to 'Workspace'
2. Click on 'Scripts'
3. Click on 'OpenPype menu'
```
PySide2/__init__.py: Unable to import shiboken2 from C:\Program Files (x86)\OpenPype\3.14.1\openpype\vendor\python\python_3, C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Comp, C:\Program Files\Blackmagic Design\DaVinci Resolve, C:\Users\PC\AppData\Local\Programs\Python\Python36\Lib\site-packages, C:\Program Files\Blackmagic Design\DaVinci Resolve\{VIRTUAL_ENV}\Lib\site-packages, C:\Program Files (x86)\OpenPype\3.14.1\openpype\vendor\python\python_3, C:\Program Files (x86)\OpenPype\3.14.1\openpype\vendor\python\common, C:\Program Files (x86)\OpenPype\3.14.1\openpype\tools, C:\Program Files (x86)\OpenPype\3.14.1, C:\Program Files\Blackmagic Design\DaVinci Resolve, C:\Program Files (x86)\OpenPype\3.14.1\dependencies, C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules, C:\Users\PC\AppData\Local\Programs\Python\Python36\python36.zip, C:\Users\PC\AppData\Local\Programs\Python\Python36\DLLs, C:\Users\PC\AppData\Local\Programs\Python\Python36\lib, C:\Users\PC\AppData\Local\Programs\Python\Python36
Traceback (most recent call last):
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Comp\__OpenPype__Menu__.py", line 20, in <module>
    result = main(os.environ)
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Comp\__OpenPype__Menu__.py", line 11, in main
    import openpype.hosts.resolve.api as bmdvr
  File "C:\Program Files (x86)\OpenPype\3.14.1\openpype\hosts\resolve\api\__init__.py", line 12, in <module>
    from .pipeline import (
  File "C:\Program Files (x86)\OpenPype\3.14.1\openpype\hosts\resolve\api\pipeline.py", line 19, in <module>
    from openpype.tools.utils import host_tools
  File "C:\Program Files (x86)\OpenPype\3.14.1\openpype\tools\utils\__init__.py", line 1, in <module>
    from .widgets import (
  File "C:\Program Files (x86)\OpenPype\3.14.1\openpype\tools\utils\widgets.py", line 3, in <module>
    from Qt import QtWidgets, QtCore, QtGui
  File "C:\Program Files (x86)\OpenPype\3.14.1\dependencies\Qt.py", line 1925, in <module>
    _install()
  File "C:\Program Files (x86)\OpenPype\3.14.1\dependencies\Qt.py", line 1873, in _install
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.
```

**Expected behavior**
Showing the OP menu to create and publish shots.

**Desktop (please complete the following information):**
 - OS: windows
 - Host: Davinci

[cuID:OP-4147]

**Comment by jakubjezek001** [comment]
Thank you for reporting the issue. Could you also enclose the Resolves environments? Thank you.

**Comment by BigRoy** [comment]
```PySide2/__init__.py: Unable to import shiboken2 from ...```

Being unable to import shiboken2 but being able to at least trigger PySide2 stands out to me that Python can find PySide2 but fails to import shiboken2 (and thus PySide2) correctly.

Can you confirm the scripts are correctly running through Python 3 in Resolve. I believe there's a preference in the application with which you can set the default python version - can you confirm the setting is set to Python 3? :)

Another workaround to avoid the setting to be required to be set to Python 3 is to change the OpenPype menu scripts extension to `.py3` instead of `.py` - it'll force Resolve and Fusion to load it with Python 3.

**Comment by jakubjezek001** [comment]
Hey @aramadan0096 what is the state of this issue. Did you managed to solve it yourself or it persists? Can we close the issue?

**Comment by aramadan0096** [comment]
> Thank you for reporting the issue. Could you also enclose the Resolves environments? Thank you.

![cccccc](https://user-images.githubusercontent.com/57462754/194437772-2d71fb1c-6052-4456-870f-a392ea64e992.png)

**Comment by aramadan0096** [comment]
> `PySide2/__init__.py: Unable to import shiboken2 from ...`
> 
> Being unable to import shiboken2 but being able to at least trigger PySide2 stands out to me that Python can find PySide2 but fails to import shiboken2 (and thus PySide2) correctly. Which could potentially happen if Python 2 tries to import a Python 3 PySide2 package.
> 
> Can you confirm the scripts are correctly running through Python 3 in Resolve. I believe there's a preference in the Resolve with which you can set the default python version - can you confirm the setting is set to Python 3? :)
> 
> Another workaround to avoid the setting to be required to be set to Python 3 is to change the OpenPype menu scripts extension to `.py3` instead of `.py` - it'll force Resolve and Fusion to load it with Python 3.
> 
> By the way, you can confirm this suspicion by doing the following in the Py3 tab in the Console:
> 
> ```python
> from PySide2 import QtWidgets
> ```
> 
> If that does work I'm pretty sure Resolve is trying to run the OpenPype menu through a Python 2 interpreter instead.

I've renamed "__OpenPype__Menu__.py" to "__OpenPype__Menu__.py3" but nothing changed, plus QtWidgets could not be imported

**Comment by aramadan0096** [comment]
> Hey @aramadan0096 what is the state of this issue. Did you managed to solve it yourself or it persists? Can we close the issue?

I'm really sorry for late response, I was just unable to access github... but my issue didn't  solved yet.
thanks for your understanding

**Comment by aramadan0096** [comment]
When I tried to run reslove individually without OP I got this problem
![nottt](https://user-images.githubusercontent.com/57462754/194443828-6f6e0acf-f54f-41b6-b1ed-048ef5969e94.png)
