### ISSUE TITLE
Maya: vray/redshift multichannel exr image output prefix 

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3956]
**Running version**
3.14.2

**Describe the bug**
when using multichannel exr output in vray (6.00.02) wrong image ouptut prefix is applied to deadline job

![image](https://user-images.githubusercontent.com/352795/194901032-2b337c75-8a02-4574-92ac-470e56a0d966.png)

**Expected behavior**
with multichannel exr we should not use `_<aov>` image prefix

there is this check in `renderproduct.py`, but for whatever reason it is not working

[cuID:OP-4214]

**Comment by BigRoy** [comment]
@m-u-r-p-h-y this is fixed by https://github.com/pypeclub/OpenPype/pull/3954

**Comment by BigRoy** [comment]
It's odd that this happens with Multichannel EXR however - which makes me assume there's still another bug present.
I feel both Redshift and V-Ray should not return `<aov> appended from the render product if it's set to render as multilayer / merged AOVs to begin with. I feel like the logic might actually be wrong there.

**Comment by m-u-r-p-h-y** [comment]
there is the logic, but I'm not able to tell why it is not working

```
        if image_format_str == "exr (multichannel)":
            # AOVs are merged in m-channel file, only main layer is rendered
            self.multipart = True
            return products
```

**Comment by BigRoy** [comment]
I feel like the bug is [here](https://github.com/pypeclub/OpenPype/blob/1255f1b57d31160f69ad1baffcd6ce335aac9077/openpype/hosts/maya/api/lib_renderproducts.py#L728-L742) since it doesn't take into account whether it's multipart/multilayer or not. The same for Redshift actually.

**Comment by antirotor** [comment]
> I feel like the bug is [here](https://github.com/pypeclub/OpenPype/blob/1255f1b57d31160f69ad1baffcd6ce335aac9077/openpype/hosts/maya/api/lib_renderproducts.py#L728-L742) since it doesn't take into account whether it's multipart/multilayer or not. The same for Redshift actually.

That's the problem there, wondering why it emerged suddenly. But it should be easy to fix.

**Comment by BigRoy** [comment]
I suspect that with the refactor to new Deadline submitter we've started relying more on the `lib_renderproducts` implementation as the "ground truth" than before to avoid scattered around duplicated logic but that the `lib_renderproducts` actually was never implemented correctly for some of the cases like these.
