### ISSUE TITLE
Deadline: extract environment subprocess failure

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#3998]
## Problem

In some cases running openpype in GlobalJopPreload plugin under Deadline fails without any message. It seems the culprit is `subprocess.check_output()` call, because when preplaced with `subprocess.call()` all works as expected.

### Solution

Proposed solution would be to change `subprocess.check_output()` to Deadline calls like `FranticX.Processes.ManagedProcess` or `Deadline.Scripting.ProcessUtils.SpawnProcess`

[cuID:2zca9kh]

**Comment by iLLiCiTiT** [comment]
BTW another issue is that we don't print out if requested openpype version is not available. That's why it's crashing without any output.
