### ISSUE TITLE
Get rid of `AVALON_HIERARCHY` and `hiearchy` key on asset

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#432]
### Description
Since we always use `asset["data"]["parents"]` for getting hierarchy there is no place where `asset["data"]["hierarchy"]` or environment `AVALON_HIERARCHY` is used. So it would be nice to remove that from code where it is set.

**Comment by mkolar** [comment]
isn't it there currently to be at least somewhat on par with the data structure of upstream avalon?

**Comment by iLLiCiTiT** [comment]
> isn't it there currently to be at least somewhat on par with the data structure of upstream avalon?

Didn't realize but yes for `AVALON_HIERARCHY`.

But the key `"hierarchy"` in asset's data is not used in code at all. We don't have to set `asset["data"]["hierarchy"]` since it's duplication of `asset["data"]["parents"]`.
