### ISSUE TITLE
Review: ability to control review length

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#482]
## Problem

When extracting **Review** video from Maya with audio, shortest of media is used to determine final video length. This is usually desirable and address situations where audio is much longer then animation.

## Solution

It is desirable to add control for artist how this situation is treated - there are 3 options:

* use shortest
* use longest
* fail if not equal

**Comment by tokejepsen** [comment]
I feel like this should be artist friendly options like;
- use audio length
- use video/playblast/timeline length

**Comment by mkolar** [comment]
we now always use the explicit frame start and frame end to set the length so this is no longer relevant
