### ISSUE TITLE
as studio I need to specify a family that will only keep one published version

### ISSUE THREAD

**Issue by mkolar** [pypeclub/OpenPype#58]
<p>Some families can contain huge amounts of data and in certain situations it is desirable to be able to automatically delete previous versions when publishing. </p>

<p>This is useful especially in combination with `master` version, where we might save a lot of data on the disk. For example animation cashes useless once new version was created.</p>
<i>[PYPE-492] created by admin</i>

[PYPE-492]: https://pypeclub.atlassian.net/browse/PYPE-492

[cuID:PYPE-1373]

**Comment by antirotor** [comment]
true. closing
