### ISSUE TITLE
Integrate Ftrack api can't integrate deleted review

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#626]
## Issue
### Ftrack plugin `IntegrateFtrackInstance` (integrate_ftrack_instances.py)
- is using for integration `"published_path"` which may not be filled if representation is tagged for deletion
- should skip representations tagged for deletion except those tagged for review and thumbnail

### When it can happen
- when ExtractReview is not processed

[cuID:PYPE-1368]

**Comment by mkolar** [comment]
I"m not sure if this was fixed, or if it's so rare, but we had no reports on it for almost two years. I think we should be able to close it as extremely low priority :)
