### ISSUE TITLE
Maya: non unicode string in publish validation

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#673]
## Bug

When publishing, sometimes Validator checking for non-unicode strings in environment is triggered, stopping publishing and forcing user to use repair action.

## Suggestion

We could automatically convert environment used during publish to unicode strings no matter of what.

```python
import os

filtered_env = {k: str(v) for k, v in os.environ.items()}
```

**Comment by mkolar** [comment]
fixed in https://github.com/pypeclub/OpenPype/pull/1045
