### ISSUE TITLE
Harmony: move server console to system tray

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#676]
## Feature

Currently when running Harmony, terminal windows is opened showing server activity. This window is useful for debugging purposes but scary for artists and it doesn't close with Harmony. And creating new Qt windows is inefficient - it would be more elegant to wrap all of this into one QApplication with server thread implemented as QThread and hide all server communication and debug output into console accessible by clicking on tray icon.

**Comment by karmakat** [comment]
Hi,
This is a great idea. This makes me think however that Pype should have a universal progress bar UI and api. In the case of launchers this really would be helpful if the shell window is helpful. As well, there are other long running processes that it is not clear what is happening. Hiding the shell in Harmony might cause problems with say localizing or even saving up a version of very large scene.
