### ISSUE TITLE
Maya: Support baking custom attributes on camera extraction

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#689]
## Feature

Add support to bake custom attributes on camera when extracting it as Maya Scene. We now support only baking of transforms to world space.

[cuID:PYPE-1134]

**Comment by mkolar** [comment]
this already work, simply by adding attributes to alembic extractor settings

**Comment by antirotor** [comment]
This issue is for extracting as Maya Scene - not alembic extractor. Sorry, it should be stated so in description.

**Comment by mkolar** [comment]
We should close this for low intereted. Even the clients originally requesting it are now using alembic for cameras, so it's a wasted effort.
