### ISSUE TITLE
Maya: Render multiple renderLayers in one farm job

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#712]
## Feature

Right now one job on farm is one write/render node. But it is more efficient to render multiple outputs at once - like masks, etc. So we should collect all output "producers" and put them into one job and publish them as subsets of the same asset in similar way AOV works in Maya.

[cuID:PYPE-1364]

**Comment by mkolar** [comment]
@antirotor have we had any request related to this recently? It's been sitting here for quite a while

**Comment by mkolar** [comment]
related to #225

**Comment by antirotor** [comment]
> related to #225

Really?

**Comment by antirotor** [comment]
I am closing it now as there isn't any real demand on it and it would only make sense in Nuke/Harmony.
