### ISSUE TITLE
Harmony: wrong publishing due to preserving context

### ISSUE THREAD

**Issue by 64qam** [pypeclub/OpenPype#818]
When a user creates a new shot copying the previous shot, the renderAnimation nodes preserve metadata from the previous shot. Therefore, it is impossible to publish the file. The renderAnimatinDefault has to be deleted from the composition and new needs to be created.

**Comment by tokejepsen** [comment]
Could this be validated on publish and repaired?

**Comment by kalisp** [comment]
Closed by https://github.com/pypeclub/avalon-core/pull/336
