### ISSUE TITLE
Harmony: Invalid render output from non-conventionally named instance

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#871]
## Bug

When rendering stuff from instance named like `fooBar_1` frame range gets mangled, producing files like `fooBar_1001,png` - this should be `fooBar_1_1001.png`. We need to modify how filename is determined by instance.

### Temporary fix:

Just rename instance so it doesn't end with numeric character.

**Comment by kalisp** [comment]
I don't think that's an issue anymore, attaching collected expected files for instance ending with a number:
![Screenshot 2021-05-17 130352](https://user-images.githubusercontent.com/4457962/118479451-50a13000-b711-11eb-8e9b-601a462179c0.png)
