### ISSUE TITLE
add option to define paht to workfile template

### ISSUE THREAD

**Issue by jezscha** [pypeclub/OpenPype#895]
**Is your feature request related to a problem? Please describe.**
At the moment each of host's prelaunch hooks need to solve possible Template.ext path and the code used is duplicated.

**Describe the solution you'd like**
Lets add the `get_anatomy_filled` and `get_workfile_plath` with template solver into the global hooks. If the template file is not found it will just simply start the host as it is doing now. Good example is in Photoshop prehook.

**Comment by jezscha** [comment]
Would this be better to add into pype2 global hooks @iLLiCiTiT ? 
Lets say `pype\hooks\global\pre_workfile_from_template.py` The idea is that this will create from template if any is found if none is found the outcome of the hook will be nothing and host will start without it.

**Comment by iLLiCiTiT** [comment]
> Would this be better to add into pype2 global hooks

Pype 2 does not have global hooks as pype 2 is support single hook on launch and it would be complicated to add this kind of feature with the way of launching applications.

In Pype 3 it is already prepared. Launch context always contain path to last workfile, if last workfile does not exist then contain path to first workfile even if does not exist yet. It is quite easy to add hook that will check existence of last workfile path and use it as destination path for template.

**Comment by mkolar** [comment]
let's add the option for this to settings
![image](https://user-images.githubusercontent.com/3333008/107237066-a08f9d00-6a26-11eb-98d4-f83d48039cf1.png)
