### ISSUE TITLE
Better error reporting on invalid anatomy data

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#946]
## Problem

If Anatomy template is changed in live project from single to multi-root setup, thing will break. This is not good idea at all but even if this happens, some warning or error should be issued to user. Currently it shows as inability to load published stuff in _VERY_ cryptic way - for example it tries to find `/root}/project/...` - notice `}` in path. This is the only indication that templates doesn't match.

[cuID:PYPE-1352]

**Comment by mkolar** [comment]
this is safe to close now considering multiroots have long been requirement.
