### ISSUE TITLE
Create Read Node in Nuke Write breaks when Nuke Project Directory is empty

### ISSUE THREAD

**Issue by jrsndl** [pypeclub/OpenPype#950]
**Describe the bug**
Avalon prefills the Nuke Project directory (Project setting) with work task directory. Create Read Node button in Nuke write node assumes this is filled and makes read node path relative to Project settings path. Empty project settings path produces wrong path

**To Reproduce**
1. Render Pype Write Node
2. Click to [Create Read] button in rendered write produces correct Read node with relative path
3. Go to project settings, remove path from the project directory
4. Select the same write node as in step 1
5. Click to [Create Read] button in rendered write produces Read node with dot after every letter. Ie //pth/to becomes ././.p.t.h./.t.o

**Expected behavior**
Empty project directory should produce absolute path in read node created by [Create Read] button

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host: Nuke 11.3

**Possible Fix**
https://github.com/pypeclub/pype/blob/aad1778935bc186aa9ac1a0274f477ea8834235b/pype/hosts/nuke/startup/write_to_read.py#L57

Checking for empty string correctly detects that Project directory is empty:
```python
if (not isinstance(project_dir, type(None))) and project_dir != "":
```

[cuID:yjx91f]

**Comment by mkolar** [comment]
@jrsndl do you have any idea if this is still a problem?
