### ISSUE TITLE
Manager: Update all to latest button

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/OpenPype#969]
**Is your feature request related to a problem? Please describe.**
When updating many containers in the manager, it takes time and clicks to select them > right-click > update to latest.

**Describe the solution you'd like**
Add a button at the top to update all outdated containers to latest version.

![Capture](https://user-images.githubusercontent.com/1860085/106766528-df41e380-6631-11eb-8e72-7ffc172607a9.PNG)

[cuID:PYPE-1209]

**Comment by mkolar** [comment]
I agree. Small thing but certainly a pleasant impact on users

**Comment by BigRoy** [comment]
For the time being I tend to recommend to:
- enable filter to outdated (top right), 
- select all
- right click > update to latest
