### ISSUE TITLE
Yeti Rig manager

### ISSUE THREAD

**Issue by mkolar** [pypeclub/OpenPype#97]
**Is your feature request related to a problem?**
We have automatic yeti rig connection to meshes in the scene via loader, but sometimes it would be useful to be a bit more explicit when doing this.

**Describe the solution you'd like**
Let's have a look at implementing https://github.com/Colorbleed/maya-yeti-rig-manager 

[cuID:PYPE-1374]

**Comment by mkolar** [comment]
@BigRoy are you guys using this yeti rig manager, or is it just prototype?

**Comment by BigRoy** [comment]
It was a prototype that we used on one production but then skipped later.

If you can set concrete goals of what it should do or how it needs to behave from an artist's point of view I'll see where I can help.

**Comment by mkolar** [comment]
I was just wondering what state it is now. We'll have a look at it and put more specs in place It is not heavily requested with the automatic connecting we have. More of a convenience.
